### ISSUE TITLE
getting unresolved idenfier in my swift project. 

### ISSUE THREAD

**Issue by laiqahmad11** [smooch/smooch-ios#101]
i am using cocoapods to install Smooch. Pod install runs successfully and i can see the downloaded files as well. Here is how my bridging header looks like.
# ifndef inTouch_Bridging_Header_h
# define inTouch_Bridging_Header_h
# import "MGMushParser.h"
# import "SwipeView.h"
# import <Smooch/Smooch.h>
# endif /\* inTouch_Bridging_Header_h */

but in my app delegate.swift file, i am getting error unresolved identifier Smooch. Not sure what i am doing wrong.

**Comment by mspensieri** [comment]
@laiqahmad11 I'm assuming there's a typo in the code you pasted because the third `#import` statement is blank, and Smooch is not included in that code snippet? Also, since you are using `#import` instead of `#include`, the `#ifndef` isn't required. Can you try this?

```
#import "MGMushParser.h"
#import "SwipeView.h"
#import <Smooch/Smooch.h>
```

**Comment by laiqahmad11** [comment]
There is no typo. i have tried copy & paste as well. pretty much all combinations.

**Comment by mspensieri** [comment]
I meant there must be a typo in what you pasted to GitHub above ^^

Anyways, couple follow-up questions:
1. Are you able to use those other Objective-C libraries correctly ? (i.e. `MGMushParser` and `SwipeView`) ?
2. Are you using `use_frameworks!` directive in your podfile?
3. Which version of the cocoapods gem do you have installed? `pod --version`

**Comment by mspensieri** [comment]
As of [v5.5.2](https://github.com/smooch/smooch-ios/releases/tag/5.5.2), bridging header is no longer required. Closing this issue
