### ISSUE TITLE
Handling 'reply' action buttons

### ISSUE THREAD

**Issue by FrankSalad** [smooch/smooch-ios#106]
> There are 4 types of supported actions : link, buy, postback, and reply.

According to [smooch docs](http://docs.smooch.io/rest/#post-message). Looks like a new feature (thanks for iterating!) I tried tapping a reply button sent to me inside the ios integrated client and I was redirected outside the app. It looks like it tries to open a browser and link me to a localhost address. 

Going back to postback buttons works, but we really like the notion of transient use-once buttons. They render and interact really nicely in Facebook Messenger.

**Comment by mspensieri** [comment]
We definitely have plans to add full support for `reply` actions to iOS. In the meantime though, you can try this snippet which will give you _most_ of the functionality of reply buttons in the meantime. The only missing pieces are that the reply message won't have the "payload" attached, and the buttons will remain attached to the message in the UI after the user taps one (but they will be inactive):

```
-(BOOL)conversation:(SKTConversation *)conversation shouldHandleMessageAction:(SKTMessageAction*)action
{
    if(![action.type isEqualToString:@"reply"]){
        return YES;
    }
    
    SKTMessage* lastMessage = [conversation.messages lastObject];
    
    if(lastMessage.actions && ([lastMessage.actions indexOfObject:action] != NSNotFound)) {
        SKTMessage* reply = [[SKTMessage alloc] initWithText:action.text];
        
        [conversation sendMessage:reply];
    }
    
    return NO;
}
```

Let me know how it goes!

**Comment by mspensieri** [comment]
Full support for reply actions was added in [v5.4.0](https://github.com/smooch/smooch-ios/releases/tag/5.4.0)
