### ISSUE TITLE
Text/photo input appearing at top of conversation view, hides intro text

### ISSUE THREAD

**Issue by beaker-sbo** [smooch/smooch-ios#109]
**Issue**:

In versions of iOS below 9.0, we're seeing that the text/photo input in the chat window is pinned to the top of the view when the view initially loads. The message history is still visible, but this hides the Intro text for new chat sessions (with no previous history), and it seems the only way to bring it back down to the bottom of the view when it isn't active/set as the first responder is to begin uploading a photo and then canceling. This issue is not reproduced in iOS 9, as far as we can see. This is present even in Smooch 4.3.0, and versions prior (we've seen it in versions as old as 3.6.0).

**STR**:
1. Open a new Smooch conversation window (we instantiate with `[Smooch newConversationViewController];`) in a project with iOS 8 as the minimum deployment target
2. Note that the input window is at the top of the view
3. Attempt to input either text or a photo, and then cancel
4. Note that the input window should now be closed, and pinned to the bottom of the view

**Expected result**:
- The view opens, and the input window is pinned to the bottom of the view until tapped to input text or upload a photo

**Actual result**:
- As in the screenshot below, the input window is pinned to the top of the view until tapped to input text or upload a photo. The intro text for conversations with little or no history is hidden from view. When dismissed/canceled, the input window is correctly pinned to the bottom of the display.

![simulator screen shot sep 1 2016 3 43 51 pm](https://cloud.githubusercontent.com/assets/6422201/18187270/fea86cb4-705c-11e6-9033-b5e9d8bf8172.png)

Thanks!

**Comment by mspensieri** [comment]
Thanks for the detailed report. I haven't been able to reproduce this behaviour with my default setup on iOS 8, can you provide more details about how you present the view controller? After the call to `[Smooch newConversationViewController]`, how is that being displayed? From the screenshot it looks like you have a custom navigation item with a hamburger menu in the top left corner - do you use something like https://github.com/John-Lluch/SWRevealViewController, or a similar alternative?

A sample project would be great, if possible

**Comment by beaker-sbo** [comment]
@mspensieri Thanks for getting back to me, apologies for being late in my own reply. We are, indeed, presenting it via our own fork of `SWRevealViewController`, in a helper class. We don't do anything particularly fancy when initializing the view, aside from adding the hamburger menu to open the rear view controller (side menu) and setting it as the main navigationController item:

`if (self.frontViewMode == SBOFrontViewModeFeedBack){
        UIViewController *lcFeedbackController = [Smooch newConversationViewController];
        lcFeedbackController.navigationItem.leftBarButtonItem = [UIBarButtonItem sbo_menuNavBarItemWithTarget:self.revealViewController action:@selector(revealToggle:)];
        UINavigationController *lcNav = [[UINavigationController alloc] initSBOWithRootViewController:lcFeedbackController];
        [self.revealViewController setFrontViewController:lcNav];`

Please let me know if you need anything else.

**Comment by wmora** [comment]
Hi @beaker-sbo, I was not able to reproduce this issue. I pushed a [modified sample project](https://github.com/wmora/SWRevealViewController/tree/smooch/RevealControllerExample) from SWRevealViewController with Smooch's conversation view [here](https://github.com/wmora/SWRevealViewController/blob/smooch/RevealControllerExample/RevealControllerProject/RearViewController.m#L148-L157) and the input is placed correctly at the bottom when running the project on iOS 8. 

Could you take a look and let me know if I missed anything?

**Comment by PatrickAdams** [comment]
We are also having issues with this but it only happens when a user uses a custom keyboard. All custom keyboards seem to break Smooch. We are presenting with `[Smooch show];`

**Comment by mspensieri** [comment]
@PatrickAdams the behaviour is the same as displayed in the initial screenshot? Are you also using `SWRevealViewController`?

**Comment by PatrickAdams** [comment]
@mspensieri No, we are not. Have you tested it with custom keyboards?

**Comment by mspensieri** [comment]
Can't say I've ever tested custom keyboards, no. I've filed the issue internally, will update here when we have more information

**Comment by PatrickAdams** [comment]
Yea, you just download a keyboard from the App Store and enable it in Settings.

**Comment by wmora** [comment]
we just released [v5.5.0](https://github.com/smooch/smooch-ios/releases/tag/5.5.0) with includes fixes to the input placement. Let us know if you're still having the issue after updating
