### ISSUE TITLE
[docs] Library not loaded: @rpath/Frameworks/Smooch.framework

### ISSUE THREAD

**Issue by anderscarling** [smooch/smooch-ios#110]
I had a rough time time tracking down this runtime error that i was getting using Smooch 4 (through Cocoapods) until I realized that my build settings for some reason did not define any 'Runtime Search Paths' (`LD_RUNPATH_SEARCH_PATHS`). In new projects they seem to have a proper value (`$(inherited)`, `@executable_path/Frameworks`),  but for some reason the setting was never there in my project created 1st May 2014 (git history checked).

Error was `Library not loaded: @rpath/Frameworks/Smooch.framework`

Maybe add this to some sort of FAQ or documentation?

**Comment by mspensieri** [comment]
Thanks for the info, we'll make sure this find its way into our docs somewhere :)

**Comment by Dids** [comment]
Just ran into this too. Google didn't help at all, so it took me literally hours to arrive here.

**Comment by anderscarling** [comment]
@Dids Happy to be of service, hope you got it working alright!

**Comment by mspensieri** [comment]
Your suggestion has been added to the FAQ section of our new docs https://docs.smooch.io/faq/ios/
