### ISSUE TITLE
Add nullability specifiers for better Swift compatibility.

### ISSUE THREAD

**Issue by williamsjj** [smooch/smooch-ios#111]
The Smooch header files need nullability specifiers for better Swift compatibility.

After upgrading to Xcode 8 w/ Smooch 5.0, running ```xcodebuild``` from the commandline will trigger this error:

```'(appToken: String!) -> SKTSettings' is not convertible to '(appToken: String!) -> SKTSettings!'```

for this invocation:

```
//Set up Smooch
Smooch.initWithSettings(SKTSettings(appToken: "key_goes_here"))
```

The problem is caused because none of the Smooch header files have nullability specifiers on their parameter or return signatures, leading the Swift compiler to lose its mind in the ambiguity (Xcode must pass an undocumented setting to Xcode build to make it work via the GUI...but that's not unusual unfortunately).

For example adding following nullability specifiers fixes the above issue:

**SKSettings.h**
```+(instancetype _Nonnull)settingsWithAppToken:(NSString* _Nonnull)appToken;```

**Smooch.h**
```+(void)initWithSettings:(SKTSettings* _Nonnull)settings;```

**Comment by wmora** [comment]
@williamsjj I'm not able to reproduce this issue. I tested it with a new Swift project on XCode 8. I also tested it with the `Use Legacy Swift Language Version` flag set to `Yes` to compile it with Swift 2.3. Maybe there's something else that's causing the issue? Could you provide the `xcodebuild` command that's giving you the error?

**Comment by williamsjj** [comment]
Are you using CocoaPods to integrate Smooch? Also are there nullability specifiers showing up for you?

**Comment by wmora** [comment]
yes, I'm using CocoaPods. Not getting any nullability specifiers

**Comment by williamsjj** [comment]
Nullability specifiers are really necessary for deterministic Swift compatibility.

**Comment by wmora** [comment]
@williamsjj you're right, and we'll add them for our next release, but we also wanted to reproduce the issue to make sure that adding the nullability annotations fixes the problem. Will let you know when it's ready

**Comment by williamsjj** [comment]
@wmora 

It looks related to whole module optimization being enabled...if it's enabled and there are no nullability specifiers I get the problem:

![image](https://cloud.githubusercontent.com/assets/119410/18565104/b2579e30-7b4b-11e6-936b-b6154737cf7a.png)

If whole module optimization is disabled **or** nullability specifiers are present, it compiles fine.

**Comment by wmora** [comment]
thank you for the detail, I will check it out and also add the specifiers

**Comment by theonetheycallneo** [comment]
Adding my error here for support:

After updating to Xcode 8 and pod installing 5.0.0, I get:

 '(appToken: String!) -> SKTSettings' is not convertible to '(appToken: String!) -> SKTSettings!'

When doing initializing Smooch framework inside the AppDelegate:

Smooch.initWithSettings(SKTSettings(appToken: "XXXXXX"))

http://d.pr/i/bXWs

**Adding nullability to the header files worked and I can now compile for App Store.

**Comment by mspensieri** [comment]
Specifiers were added in v5.0.1

**Comment by williamsjj** [comment]
Thanks you @mspensieri! They work great.
