### ISSUE TITLE
'(appToken: String!) -> SKTSettings' is not convertible to '(appToken: String!) -> SKTSettings!'

### ISSUE THREAD

**Issue by theonetheycallneo** [smooch/smooch-ios#112]
After updating to Xcode 8 and pod installing 5.0.0, I get:

 '(appToken: String!) -> SKTSettings' is not convertible to '(appToken: String!) -> SKTSettings!'

When doing initializing Smooch framework inside the AppDelegate:

Smooch.initWithSettings(SKTSettings(appToken: "XXXXXX"))

http://d.pr/i/bXWs

**Comment by williamsjj** [comment]
@theonetheycallneo This be the problem: https://github.com/smooch/smooch-ios/issues/111

**Comment by theonetheycallneo** [comment]
Adding the nullability headers worked for me.  I forked 5.0.0 and manually included without using pod install.  Thank you @williamsjj

**Comment by williamsjj** [comment]
@theonetheycallneo Glad to help! I banged my head on that for a few hours till I figured it out. Oddly, running Archive from the Xcode UI didn't exhibit the problem for me...only from xcodebuild when "Whole Module Optimization" was enabled (sans nullability).

**Comment by mspensieri** [comment]
A build with nullability specifiers is in the works, closing this issue since it's a dup of #111
