### ISSUE TITLE
Text field hides under keyboard

### ISSUE THREAD

**Issue by karol-wieczorek** [smooch/smooch-ios#113]
Hi,

I'd like to push view controller with smooch into navigation controller with tab bar. This is how my code looks like:

```
UIViewController *smoochVC = [Smooch newConversationViewController];
smoochVC.hidesBottomBarWhenPushed = YES;
[self.navigationController pushViewController:smoochVC animated:YES];
```

But then, "Type a message..." text field is covered by keyboard:
![img_0992](https://cloud.githubusercontent.com/assets/8514200/18745125/54bf31e0-80c1-11e6-843e-83c14e2dc000.PNG)

![img_0993](https://cloud.githubusercontent.com/assets/8514200/18745127/5bff6ff6-80c1-11e6-91c6-017e1f92fa0b.PNG)

I'm testing on iPhone 6S, iOS 9.3.5.

Thanks for help.

**Comment by mspensieri** [comment]
This issue should be fixed in [v5.4.0](https://github.com/smooch/smooch-ios/releases/tag/5.4.0). Please re-open if the issue persists
