### ISSUE TITLE
Stop smooch notifications

### ISSUE THREAD

**Issue by ZalyalovIldar** [smooch/smooch-ios#115]
Good day. I can't find any function to disable notification if user logout or something else. Could you help me with that?

**Comment by wmora** [comment]
Hi @ZalyalovIldar, please take a look at [Configuring push notifications](http://docs.smooch.io/ios/#configuring-push-notifications) in the docs. It tells you the required steps to handle the push notifications yourself.

**Comment by mspensieri** [comment]
Whether or not to send notifications should be automatically handled by the Smooch platform if your app is using the `login:jwt:` and `logout` methods.

When you switch users by calling `login:jwt:` or `logout`, all other users on the same device are deactivated and should no longer receive push notifications - only the active user will receive them.

Note that calling `logout` if the current user is already anonymous (i.e. does not have a `userId` assigned) is a no-op.

**Comment by ZalyalovIldar** [comment]
Yes, unfortunately logout doesn't work to stop notification receiving.

**Comment by mspensieri** [comment]
Can you provide a bit more information?

* A specific `userId` that is still receiving notifications after logout
* The email address associated to your smooch account to help me find your user
* Sample code showing how/where you are using login/logout
* The SDK version you are using

**Comment by ZalyalovIldar** [comment]
* In fact any user that logout is still receiving notifications until new user login on the same device.
*could I provide email personally to your email? 
*`func login(_ userID: String) {
        Smooch.login(userID, jwt: nil)
    }`
*Smooch 5.0.0

**Comment by mspensieri** [comment]
You can send your info to help@smooch.io

**Comment by mspensieri** [comment]
Followed up by email

**Comment by ZalyalovIldar** [comment]
If some one will get similar bug, i fixed it by added   Smooch.setPushToken(Data()) - just send incorrect push token when logout user, to stop receiving notifications after logout 🍭
