### ISSUE TITLE
Use of beginBackgroundTaskWithExpirationHandler in the sdk

### ISSUE THREAD

**Issue by mtrip** [smooch/smooch-ios#116]
I was debugging some background code in my app while smooch was down due to last week DDoS attack on DYN and I noticed in my log that the smooch SDK was trying to reconnect to smooch servers every 10s, while the app was in background, and never stopped doing this. AFAIK this can only be achieved by calling  beginBackgroundTaskWithExpirationHandler recursively which is against Apple rules.
Can you confirm the behaviour?

**Comment by mspensieri** [comment]
I can confirm that when the `init` call fails, the SDK will automatically retry every 10s for a maximum of 5 minutes. However, we don't attempt to schedule any background tasks in our SDK for any reason, so I'm not sure where this behaviour is coming from.

The 10s retry is scheduled using a simple `NSTimer`

**Comment by mtrip** [comment]
I can reproduce it on a device by just turning off wifi/data: I launch the app and then I put it in background and I see this in my log every 10s:
_<SMOOCH::ERROR> An unexpected error occurred during initialization. Retrying in 10 seconds... 
Error: The Internet connection appears to be offline. 
Response: (null)_  

I created a simple timer on the main thread, and it was still firing in the background. Apparently the os gives you some time to run it without using beginBackgroundTaskWithExpirationHandler

However you should unschedule any timer when the app goes in the background as the os may decide to kill the app anytime. My app makes use of background location (and is designed to be used offline) so I want to avoid any scenario where the os would kill the app

**Comment by mspensieri** [comment]
Thanks for the details. I've filed the issue internally, will close this issue when it's fixed

**Comment by wmora** [comment]
@mtrip we just released version 5.2.1 which fixes this issue
