### ISSUE TITLE
Smooch notification still appear when app active after appdelegate swizzling disabled

### ISSUE THREAD

**Issue by EllinaKuznetcova** [smooch/smooch-ios#118]
So, I am debugging on iOS 10 and trying to get control on showing notifications. I'm trying to disable swizzling this way:
```   
        let settings = SKTSettings(appToken: smoochToken)
        settings.userId = "\(user.id)"
        settings.enableAppDelegateSwizzling = false
        Smooch.initWith(settings)
        Smooch.login("\(user.id)", jwt: nil) 
```

But, unfortunately, it didn't work and Smooch notification view still appears on screen. Is there a way to disable showing this view?

**Comment by mspensieri** [comment]
The `enableAppDelegateSwizzling` flag is not intended to be used to change behaviour, it's intended to be used as a workaround when your application needs to do its own handling on the app delegate methods that Smooch overrides. If you look at the [documentation](http://docs.smooch.io/api/ios/Classes/SKTSettings.html#//api/name/enableAppDelegateSwizzling) for that method, it actually outlines steps that your app must follow to ensure that remote notifications continue to function correctly.

If you'd like to hide the in-app notification view, then you should set an `SKTConversationDelegate` object and override the [conversation:shouldShowInAppNotificationForMessage:](http://docs.smooch.io/api/ios/Protocols/SKTConversationDelegate.html#//api/name/conversation:shouldShowInAppNotificationForMessage:) method.

```
let settings = SKTSettings(appToken: smoochToken)
settings.userId = "\(user.id)"
Smooch.initWith(settings)

Smooch.conversation()?.delegate = self

/* ... */ 

func conversation(_ conversation: SKTConversation, shouldShowInAppNotificationFor message: SKTMessage) -> Bool {
    return false
}

```

**Comment by EllinaKuznetcova** [comment]
Thank you!
