### ISSUE TITLE
Custom action upon tapping messages notification banner

### ISSUE THREAD

**Issue by clayellis** [smooch/smooch-ios#124]
In the same way that you may choose to use `newConversationViewController()` over `show()`, Smooch should introduce some override point for the presentation of the conversation view controller when the user taps the dark message notification banner that comes down from the top of the screen. Currently, as far as I can tell, there is no good way to override the default `show()` once the banner is tapped to handle our own presentation of the conversation view controller.

Am I missing something here?

**Comment by mspensieri** [comment]
I think you're looking for [`conversation:shouldShowForAction:`](https://docs.smooch.io/api/ios/Protocols/SKTConversationDelegate.html#//api/name/conversation:shouldShowForAction:)

```objc
-(BOOL)conversation:(SKTConversation *)conversation shouldShowForAction:(SKTAction)action
{
    // Display the conversation however you want
    
    return NO;
}

```
