### ISSUE TITLE
Pre-fill UItextField with some text

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#125]
Is there any ability we can pre-fill the UItextField with some text before calling `Smooch.show()`

**Comment by mspensieri** [comment]
There isn't at the moment, but I've filed this as a feature request for the team to discuss

**Comment by mspensieri** [comment]
You can automatically send a message on behalf of the user using the [`sendMessage:`](https://docs.smooch.io/api/ios/Classes/SKTConversation.html#//api/name/sendMessage:) API though

**Comment by qadirsuh** [comment]
Thanks.

**Comment by wmora** [comment]
This is supported in [v6.10.0](https://github.com/smooch/smooch-ios/releases/tag/6.10.0)

**Comment by qadirsuh** [comment]
Wow! Thanks @wmora for update.
Is there any documentation for how to implement this. :)

Regards
Qadir

**Comment by qadirsuh** [comment]
Thanks :)
