### ISSUE TITLE
Close smooch ios widget on payload click

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#126]
Can we close the smooch widget on payload click event?
Example:
Like we send message to our customers like below from slack
`Do you want to close the chat window %[YES](postback:close_chat) %[NO](postback:do_not_close_chat)`

and this will be rendered to our customers as image given below
![close](https://cloud.githubusercontent.com/assets/14326497/22290816/d7b64348-e324-11e6-951a-2b91dd942f07.png)

upon click YES chat window should be closed, is there any possibility to do this?
Can we do this as simple as possible using payload, links or reply buttons
http://blog.smooch.io/how-to-make-buttons-images-payments-with-smooch-a-syntax-cheatsheet/

**Comment by mspensieri** [comment]
Sure! You can do this using the [`conversation:shouldHandleMessageAction:`](https://docs.smooch.io/api/ios/Protocols/SKTConversationDelegate.html#//api/name/conversation:shouldHandleMessageAction:) method

Here's an example using a `postback` type button, but any type would work

```
-(BOOL)conversation:(SKTConversation *)conversation shouldHandleMessageAction:(SKTMessageAction *)action
{
    if([action.type isEqualToString:SKTMessageActionTypePostback] && [action.payload isEqualToString:@"YES"]) {
        [Smooch close];
        return NO;
    }
    
    return YES;
}
```

**Comment by qadirsuh** [comment]
Swift version of this code. please

**Comment by mspensieri** [comment]
```swift
func conversation(_ conversation: SKTConversation, shouldHandle action: SKTMessageAction) -> Bool {
    if (action.type == SKTMessageActionTypePostback && action.payload == "close_chat") {
        Smooch.close();
        return false;
    }
    
    return true;
}
```

Also make sure the `SKTConversationDelegate` property is set correctly,

```swift
Smooch.conversation()?.delegate = self;
```

**Comment by qadirsuh** [comment]
getting error :(

`Value of type 'SKTMessageAction' has no member 'payload'`

https://www.dropbox.com/s/ga74kss65bvhixq/Screenshot%202017-02-11%2000.49.59.png?dl=0

**Comment by wmora** [comment]
@qadirsuh which version of Smooch are you using? `SKTMessageAction.payload` was introduced in version 5.4.0

**Comment by qadirsuh** [comment]
where can i see it, I had installed it from pods
`pod 'Smooch'`

**Comment by wmora** [comment]
you should see it in the `Podfile.lock` file in your project's root directory. If the version is lower than 5.4.x run `pod update` to install the latest version

**Comment by qadirsuh** [comment]
Wow! thanks @wmora . Yes its `Smooch (5.3.0)`
