### ISSUE TITLE
Can we hide the StatusBar in smooch ios widget

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#127]
Can we hide the StatusBar in smooch ios widget
![status bar smooch](https://cloud.githubusercontent.com/assets/14326497/22327347/8b4d68f6-e3d8-11e6-9a20-2b7b9d989d3a.png)

traditionally we do below to hide the status bar from our viewController,

```
override var prefersStatusBarHidden : Bool {
        return true
}
```

I need this, because status bar is hidden in our whole app.

**Comment by mspensieri** [comment]
There isn't a way to tell the Smooch view controller to hide the status bar, but it will obey whatever app-wide settings your application uses. For instance, you can set these values in your info.plist to hide the status bar for your entire application:

![screen shot 2017-01-26 at 9 17 09 am](https://cloud.githubusercontent.com/assets/2286852/22334328/5fbe2994-e3a8-11e6-9ddc-d5e4ddfd94a3.png)

Or use the `isStatusBarHidden` property of the `UIApplication` class to hide/show the status bar at runtime

```
UIApplication.shared.isStatusBarHidden = true;
```

http://stackoverflow.com/a/9053346/3482071

**Comment by qadirsuh** [comment]
Wow! I didn't know this. Thank you very much. :)

**Comment by qadirsuh** [comment]
I tried the following method in my didFinishLaunchingWithOptions of appDelegate but didn't worked
`UIApplication.shared.isStatusBarHidden = true;`

the first method (with info.plist) worked like charm.

Thanks again.
