### ISSUE TITLE
Dynamically change userID

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#132]
I am trying to change smooch user id dynamically (while app is running). to clear the previous chat and start a new conversation.

here is my code.

```
func initSmooch(userID:String){
        smoochSettings = SKTSettings(appToken: AppUtils.smooch_app_token_staging) 
        smoochSettings?.userId = userID // To save userID based conversations in jamesApp smooch widget
        Smooch.initWith(smoochSettings!);        
    }
```

but its showing me the same conversations.

_Note: I remember previous version of smooch I was getting error saying somthing like.. smooch init more than once is not allowed. after pod update I am not getting that error message._ 

Every time I have to restart my app to make this work. I need to clear the chat and start new conversation in real time.

**Comment by jpjoyal** [comment]
[`Smooch.login`](https://docs.smooch.io/api/ios/Classes/Smooch.html#//api/name/login:jwt:) and [`Smooch.logout`](https://docs.smooch.io/api/ios/Classes/Smooch.html#//api/name/logout) is what you are looking for. Also check out our [Switching Users](https://docs.smooch.io/guide/multi-client-users/#switching-users) section of our guide for more details.

**Comment by qadirsuh** [comment]
Done. thanks

**Comment by qadirsuh** [comment]
I am trying to logout and login dynamically, suddenly I  am getting following log errors and my user not logouts. 
`2017-10-10 12:56:09.943411+0500 jamesAppV2[295:33338] <SMOOCH::INFO> Logout called, but no user was logged in. Ignoring!
2017-10-10 12:56:09.943625+0500 jamesAppV2[295:33338] <SMOOCH::WARNING> Login called with nil or empty jwt. Ignoring!
2017-10-10 12:56:09.943984+0500 jamesAppV2[295:33338] <SMOOCH::INFO> Logout called, but no user was logged in. Ignoring!
2017-10-10 12:56:09.944068+0500 jamesAppV2[295:33338] <SMOOCH::WARNING> Login called with nil or empty jwt.`

I have update my project swift 4 and updated smooch too.

here is my code. 

`// Call smooch logout and login after 3 sec min
            let when = DispatchTime.now() + 3 // change 3 to desired number of seconds
            DispatchQueue.main.asyncAfter(deadline: when) {

                // Your code with delay
                Smooch.logout();
                Smooch.login(guest_id, jwt:"")

                let fullNameArr = guest_name.characters.split{$0 == " "}.map(String.init)

                if(fullNameArr.count > 1){

                    SKTUser.current()?.firstName = fullNameArr[0]
                    SKTUser.current()?.lastName = fullNameArr[1]

                }else{

                    SKTUser.current()?.firstName = fullNameArr[0]
                    SKTUser.current()?.lastName = fullNameArr[0]

                    let fullNameArr = guest_name.characters.split{$0 == "-"}.map(String.init)

                    if(fullNameArr.count > 1){

                        SKTUser.current()?.firstName = fullNameArr[0]
                        SKTUser.current()?.lastName = fullNameArr[1]
                    }
                }
            }`

**Comment by mspensieri** [comment]
@qadirsuh Based on your code sample

```swift
Smooch.login(guest_id, jwt:"")
```

And your log output

```
<SMOOCH::WARNING> Login called with nil or empty jwt. Ignoring!
```

It seems you are not passing a JWT to the `login` API. JWTs are required in Smooch v6.0.0 and above when calling `login`, as stated in the [release notes](https://github.com/smooch/smooch-ios/releases/tag/6.0.0)

> `jwt` credential is now required when calling the `login:jwt:completionHandler:` API. You can no longer assign `userId`s to users without using a JWT to secure the userId. A call without a JWT will be ignored (as indicated in the log output that you pasted), so logging out will also have no effect.

See https://github.com/smooch/smooch-ios/issues/168 for some information on how to generate JWTs

**Comment by qadirsuh** [comment]
@mspensieri I am getting issue on initSmooch. please see this question
https://github.com/smooch/smooch-ios/issues/172
