### ISSUE TITLE
Change the banner text in chat widget

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#133]
Is there any way to change the text on the top of the chat widget i.e

https://www.dropbox.com/s/jdpmtwstv00yj7c/Screenshot%202017-02-23%2013.51.11.png?dl=0

**Comment by mspensieri** [comment]
You can customize any strings that Smooch displays by creating a `SmoochLocalizable.strings` file and overwriting the keys that you don't like.

See the [Customization section](https://docs.smooch.io/guide/native-ios-sdk/#strings-customization) of the docs for more info and full list of keys

**Comment by qadirsuh** [comment]
Ohh wow! smooch is complete a package ;)

one more thing to ask I have integrated smooch via pods. so how can I create `SmoochLocalizable.strings` and override that string?

**Comment by mspensieri** [comment]
You create the file in your application's main bundle, just like any other asset you would use for your application. Smooch will find it there
