### ISSUE TITLE
Conversation view controller with a tab bar doesn't update messages on tab change

### ISSUE THREAD

**Issue by janweinkauff** [smooch/smooch-ios#134]
# Context

I'm using an instance of the conversation view controller created by `newConversationViewController()`.
This instance is added as the root view controller of an `UINavigationController` to a tab bar.

Example:
Tab 0: UIViewController
Tab 1: UINavigationController -> conversation view controller
Tab 2: UIViewController

# Problem

If a message is received while I'm in Tab 1, the conversation view controller will update the messages as expected.

But when I'm in tab 0 or 2 and a message is received, the conversation view controller will not update messages if I switch back to Tab 1.

# Things I tried

I tried to call `loadPreviousMessages` and `markAllAsRead` before switching to Tab 1.

The only thing that worked was to create a new instance everytime the tab bar switches back to Tab 1.

# Question

Is there a way to force the conversation view controller to update messages?

**Comment by mspensieri** [comment]
This should be fixed in [v5.5.2](https://github.com/smooch/smooch-ios/releases/tag/5.5.2)

**Comment by janweinkauff** [comment]
Perfect, update messages works now! Thank you very much. :-) 

Note: The scroll view doesn't move down to the new message. The user has to scroll.
Should I create a new issue?

**Comment by wmora** [comment]
Sure! Open a new issue
