### ISSUE TITLE
app crash when try "Use Last Photo Taken"

### ISSUE THREAD

**Issue by romanfurman6** [smooch/smooch-ios#135]
Application is getting crashed on clicking the 'Use Last Photo Taken' 
But everything is cool when firstly i send message(text) and then photo
i read docs https://docs.smooch.io/guide/native-ios-sdk/
and add request Photo permissions to info.plist
Thanks ;)

**Comment by wmora** [comment]
We released [v5.5.2](https://github.com/smooch/smooch-ios/releases/tag/5.5.2) fixing this crash
