### ISSUE TITLE
Scroll view doesn't move down to a new message

### ISSUE THREAD

**Issue by janweinkauff** [smooch/smooch-ios#136]
# Context

I have a tab bar where one tab is based on the smooch conversation view controller.

Example:
Tab 0: UIViewController
Tab 1: UINavigationController -> conversation view controller
Tab 2: UIViewController

# Problem

When I'm not  Tab 1 and a new message arrives. I switch back to Tab 1 the messages are updated but the scroll view dosen't move down to new newest message.

**Comment by wmora** [comment]
Fixed in [5.6.7](https://github.com/smooch/smooch-ios/releases/tag/5.6.7)
