### ISSUE TITLE
Can Smooch initialize with different apptoken on One App ?

### ISSUE THREAD

**Issue by abadikaka** [smooch/smooch-ios#137]
Hi guys.. i have question about Smooch.
My company have 3 off different apptoken that representing their partner, and they want the app to be able to chat to this different apptoken in 1 iOS or android app
I already provided a list view to the partner itself, and when i click on one of the partner it able to initialize the Smooch with this first partner.
Then when i click the other partner, it gv me an error that smooch already initialize even if i send different apptoken. Then i am trying to create an array of Smooch Class , but i realize that i cant create variable of Smooch itself

Example :

`var smooch = Smooch.init(withSettings:xxx)` --> this cause an error if that Smooch.init is a void function.

they also want to the app able to get push notification from different message coming from different partner that already initialize. 

but then before i go further, is it possible to Smooch to handle that ? or at least am i able to initialize Smooch with different apptoken on one App ?

**Comment by mspensieri** [comment]
The SDK can only be initialized once. To be able to change the app token, you'd need to kill the process and restart the app with a new app token.

> they also want to the app able to get push notification from different message coming from different partner that already initialize.

This is possible if you configure the same push certificate for all 3 Smooch apps. However, if you're running 3 different app tokens in the same app, then push notifications can still be sent for an app token that is currently "logged out"

**Comment by abadikaka** [comment]
@mspensieri if the sdk only can be initialized once than it means i cant running smooch instance with those 3 apptoken on 1 app ? 
but in ur last statement u said that we could running 3 different apptokens in the same app (haha little confuse about this one) ?

is there any way to like deinitialize and after i logout or close or not use one of the apptoken , then i click on different apptoken and start the smooch with those apptoken ? Thank you

**Comment by mspensieri** [comment]
It's possible to have push notifications from different app tokens going to the same app, but it's not possible to change the app token _at runtime_. The only way to switch app tokens is to restart the app completely, and initialize with the new app token

**Comment by abadikaka** [comment]
@mspensieri okay thank you

**Comment by abadikaka** [comment]
@mspensieri one more question. So if i receive message from another apptoken i can receive or get the message on the app, but i cant reply them or open smooch on current running app, bcs it cant initialize with different app token on running time. Is it correct ?

**Comment by mspensieri** [comment]
Yes, you can receive push notifications if the app is in the background or closed, but to be able to see the messages in the app, or to reply, the SDK needs to be initialized with the correct app token

**Comment by abadikaka** [comment]
@mspensieri  okay..
i just look in android u have .destroy().. what is the same functiin in ios which is the same ability with destroy ?

**Comment by abadikaka** [comment]
@mspensieri  ah i found smooch-helpkit. but is it compatible with swift ?

**Comment by abadikaka** [comment]
@mspensieri in android, i could destroy the smooch by .destroy() when second call then re-initialize it using different apptoken without closing or kill the app.
but in iOS there is no destroy yet ? or it is fixed if there is no way to do it in iOS ? thank you..

**Comment by mspensieri** [comment]
Hmm yes the Android SDK has a `destroy` function but iOS does not. I'll mark that as a feature request!

**Comment by abadikaka** [comment]
@mspensieri. Thank you so much. I hope will be added soon :D . Really wanna make my app can change the apptoken in running time as well like in android.. thank you !

**Comment by abadikaka** [comment]
@mspiensieri and do u already know the Eta for this feature yet probably ? Estimation time for the feature ? Let me know if smooch team has already have the estimation for it.. :)

**Comment by mspensieri** [comment]
I don't really have a timeline to share. I've re-opened this issue, will update here when it gets implemented

**Comment by wmora** [comment]
A `destroy` method has been added in version [5.6.0](https://github.com/smooch/smooch-ios/releases/tag/5.6.0)

**Comment by abadikaka** [comment]
Thanks ! Very helpful function ..
