### ISSUE TITLE
webhook (Delivery Successes) not called

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#139]
I am trying to log all webhook events of smooch. i.e 

```
App User messages: A new message of role appUser was sent (usually coming from a messaging channel)
App Maker messages: A new message of role appMaker or whisper was sent (usually from a business system or via Whispers)
All messages: A new message of any role was sent
Conversation start: When a user opts in to start receiving messages
Conversation read: When a user reads a conversation
Postbacks: A user clicked on a postback action button
AppUser Merge: When two or more users are merged into one
Delivery Successes: When a message is successfully delivered to a channel
Delivery Failures: When a message fails to be delivered to a channel
Payment Successes: When a payment is successfully paid from channel
All Triggers: When any of the above triggers occurs
```

I have created a webhook for Delivery Successes event in smooch see image.
https://www.dropbox.com/s/k8hbnuvxgbge2y7/Screenshot%202017-02-22%2018.08.52.png?dl=0

This is not getting called when I send message to smooch-ios chat widget from slack or front.

here is my nodejs code

```
/* delivery_successes 
Delivery Successes: When a message is successfully delivered to a channel
*/
app.post('/delivery_successes', function(req, res, next) {

    console.log('delivery_successes: called');
    const trigger = req.body.trigger;
    console.log("trigger: " + trigger);

    switch (trigger) {
        case 'delivery:success':
            console.log('delivery:success trigger called');
            //handleBusinessMessages(req, res);
            res.end();
            break;

        default:
            //console.log('Ignoring unknown webhook');
    }
});

```

I have confirmed this is called when I send `message via slack or front to facebook`. but this is not getting called when I send message to smooch-ios chat widget.

Is there anything wrong or missing?

**Comment by qadirsuh** [comment]
Its also not called when sending message via slack/front to web messaging.

**Comment by mspensieri** [comment]
This is intended behaviour. The Smooch SDKs (iOS, Android, Web) fetch the conversation history directly using the public [Get Messages](https://docs.smooch.io/rest/#get-messages) API - there is nothing to _deliver_, hence no delivery webhooks.

As soon as a message is accepted by Smooch, the SDK can read it via the API, and therefore "delivery" was successful - no need for a webhook in this case. So, in the case of SDKs, the `delivery:*` webhooks won't be fired. When a `message:*` webhook is received, the messages should already be visible on SDKs, and any other consumer of the public API.

**Comment by qadirsuh** [comment]
Ohh.. thanks for making me clear. 
Can you tell me which webhook calls are supported by the SDK and which are not?

**Comment by mspensieri** [comment]
Everything except `delivery:*` and `conversation:start` can happen in the context of an SDK

**Comment by qadirsuh** [comment]
OK. thanks you for your time :)
