### ISSUE TITLE
API for incoming messages details

### ISSUE THREAD

**Issue by genadyo** [smooch/smooch-ios#140]
Hey,

Is there a way for me to know my users have incoming messages?
I want to mark it on my UI so they can find it.

Thank you.

**Comment by mspensieri** [comment]
Check out the documentation for [`SKTConversationDelegate`](https://docs.smooch.io/api/ios/Protocols/SKTConversationDelegate.html) protocol, which includes hooks for many different conversation events.

Sounds like the specific methods you're looking for are [`conversation:didReceiveMessages:`](https://docs.smooch.io/api/ios/Protocols/SKTConversationDelegate.html#//api/name/conversation:didReceiveMessages:) and [`conversation:unreadCountDidChange:`](https://docs.smooch.io/api/ios/Protocols/SKTConversationDelegate.html#//api/name/conversation:unreadCountDidChange:)

You can also read the [`unreadCount`](https://docs.smooch.io/api/ios/Classes/SKTConversation.html#//api/name/unreadCount) directly off of [`SKTConversation`](https://docs.smooch.io/api/ios/Classes/SKTConversation.html)

**Comment by genadyo** [comment]
Thank you, I guess I missed it.
