### ISSUE TITLE
Clear History

### ISSUE THREAD

**Issue by dtrikam1** [smooch/smooch-ios#141]
I have implemented a log out button within my application, but am currently unable to clear the existing history of the chat bot. Is it possible to do this?

**Comment by wmora** [comment]
See https://github.com/smooch/smooch-ios/issues/132#issuecomment-278343365 and let us know if it works

**Comment by bre7** [comment]
Bump. Is there no way to do this for anon users ?

**Comment by mspensieri** [comment]
@bre7 you can use the [Delete Messages API](https://docs.smooch.io/rest/#delete-messages) to clear the conversation history for any user, even anonymous users.
