### ISSUE TITLE
Swift 3.1 release please!

### ISSUE THREAD

**Issue by scottrhoyt** [smooch/smooch-ios#144]
For us carthage users. Thanks.

**Comment by mspensieri** [comment]
Hey @scottrhoyt I'm not sure I understand your request, are you having problems compiling with Swift 3.1? We just tested the latest version of the SDK with Swift 3.1 and aren't seeing any problems with it, can you give a bit more information please?

**Comment by scottrhoyt** [comment]
I'm sorry. I had a Carthage installation problem and had assumed it was a Swift version incompatibility issue, but I see now that smooch doesn't even use Swift. We fixed the issue on our side. Thanks!
