### ISSUE TITLE
Translation in French ? Specially for emails.

### ISSUE THREAD

**Issue by ganael** [smooch/smooch-ios#149]
Hello ! We are in France and we send email from slack to answer clients who have chosen to have an answer via email. Our customer care rep on Slack is named "Justine" and our Smooch account is named "Mr Barbier" so we would like to display "Justine pour Mr Barbier" as a sender of our answer but we have "Justine from Mr Barbier" ... would we have a way to change this "from" into a "pour" ??

By the way, concerning the chat elements in French, here is a translation : 

const INITIAL_STATE = {
text: {
headerText: 'Comment puis-je vous aider ?',
inputPlaceholder: 'Tapez votre message...',
sendButtonText:  'Envoyer',
introductionText: 'Je suis là pour vous aider, posez-moi toutes vos questions !',
introAppText: ‘Ecrivez-nous ici ou depuis votre chat préféré.',
settingsText: 'Vous pouvez nous laisser votre adresse email pour que nous vous répondions dès que possible.',
settingsReadOnlyText: 'Nous vous recontacterons à cette adresse email très prochainement.',
settingsInputPlaceholder: 'Votre adresse email',
settingsSaveButtonText: 'Sauver',
settingsHeaderText: 'Paramètres',
settingsNotificationText: 'Si nous tardons à vous répondre, vous pouvez <a href data-ui-settings-link>nous laisser votre adresse email</a>.',
actionPaymentError: 'Une erreur s\'est produite lors du paiement. <br> S\'il vous plaît, essayez de nouveau avec cette carte ou avec une nouvelle carte.',
actionPaymentCompleted: 'Paiement réussi !',
actionPostbackError: 'Une erreur s\'est produite, veuillez essayer de nouveau.',
messageError:  'Une erreur s\'est produite lors de l\'envoi de votre message, veuillez essayer de nouveau.',
invalidFileError: 'Seules les images sont acceptées. Veuillez choisir une image avec un des formats suivants : jpg, jpeg, png, gif, or bmp.',
messageIndicatorTitleSingular: '({count}) Nouveau message',
messageIndicatorTitlePlural: '({count}) Nouveaux messages',
connectNotificationText: 'Soyez notifié(e) dans vos autres chats quand vous aurez une réponse.',
notificationSettingsChannelsTitle:  'Autres applications',
notificationSettingsChannelsDescription:  'Vous pouvez aussi nous contacter avec l\'app ou le chat de votre choix.',
notificationSettingsConnectedAs:  'Connecté en tant que {username}',
notificationSettingsConnected: 'Connecté',
viberqrcodejerror: 'Une erreur s\'est produite avec votre QR code Viber. Veuillez réessayer.',
wechatQRCodeError: 'Une erreur s\'est produite avec votre QR code WeChat. Veuillez réessayer.',
messengerChannelDescription: 'Connectez vous à votre compte Facebook Messenger pour y recevoir notre réponse, et pour prolonger cette conversation sur Facebook.',
frontendEmailChannelDescription: 'Pour nous parlez par email, n’hésitez pas à nous envoyer un message sur notre adresse email et nous vous répondrons dès que possible.'
smsChannelDescription:  ‘Entrez votre numéro pour recevoir notre réponse et prolonger cette conversation par SMS.',
smsChannelPendingDescription: 'Vérifier vos messages sur le {number} pour confirmer votre numéro de téléphone.',
telegramChannelDescription: 'Connectez vous à votre compte Telegram pour y recevoir notre réponse et prolonger cette conversation sur Telegram.',
wechatChannelDescriptionMobile: ‘Connectez votre compte WeChat pour y notre réponse et pour prolonger cette conversation sur WeChat. Pour commencer, sauvegardez cette image de QR code et chargez là dans : <a href=\'weixin://dl/scan\'>QR code scanner</a>.',
wechatChannelDescription: 'Connectez votre compte WeChat pour y recevoir notre réponse et pour prolonger cette conversation sur WeChat. Pour commencer, scandez ce QR Code en utilisant l\'app WeChat.',
lineChannelDescription:  'Pour nous parler avec LINE, scannez ce QR code en utilisant l\'app LINE et envoyez nous un message.',
viberChannelDescriptionMobile:  ‘Connectez votre compte Viber pour recevoir une notification quand vous aurez une réponse, et pour prolonger cette conversation sur Viber. Pour commencer, installez Viber et cliquez sur Connexion.',
viberChannelDescription: 'Connectez votre compte Viber pour recevoir une notification quand vous aurez une réponse, et pour prolonger cette conversation sur Viber. Pour commencer, scannez ce QR code en utilisant l\'application Viber.',
smsInvalidNumberError: 'Votre numéro de téléphone n\'est pas valide. Veuillez essayer de nouveau.',
smsTooManyRequestsError:  'Une demande de connection à ce numéro vient d\'être postée. Veuillez réessayer dans {minutes} minutes.',
smsTooManyRequestsOneMinuteError: 'Une demande de connection à ce numéro vient d\'être postée. Veuillez réessayer dans une minute.',
smsBadRequestError:  ’Nous n\'avons pas réussi à communiquer avec ce numéro. Veuillez essayer de nouveau, ou utiliser un autre numéro.',
smsUnhandledError: 'Petit bug. Veuillez réessayer.',
smsPingChannelError:  'Une erreur s\'est produite lors de l’envoi d\'un message sur votre numéro.'
smsLinkCancelled:  'Le lien vers {appUserNumber} a été annulé.',
smsLinkPending:  'En cours',
smsStartTexting:  'Discuter par textos',
smsChangeNumber:  'Changer mon numéro',
smsSendText:  'Envoyez moi un texto!',
smsContinue: 'Continuer',
smsCancel:  'Annuler',
transferError:  'Une erreur s\'est produite lors de la génération de ce lien. Veuillez réessayer.',
fetchingHistory:  'Recherche dans l\'historique...',
fetchHistory:  'Remonter l\'historique',
clickToRetry: 'Message non reçu. Cliquez pour ré-essayer.',
tapToRetry: 'Message non reçu. Cliquez pour ré-essayer.',
locationSendingFailed: 'Ne peut pas poster de localisation',
locationServicesDenied:  'Ce site ne peut pas accéder à votre localisation. Autorisez cet accès dans vos paramètres ou saisissez votre localisation.',  
locationNotSupported:  'Votre navigateur n’autorise pas la géolocalisation. N\'hésitez pas à saisir votre localisation.',
locationSecurityRestriction: 'Ce site ne peut pas accéder à votre localisation. N\'hésitez pas à saisir votre localisation.'
}
};

**Comment by jpjoyal** [comment]
Merci pour la traduction @ganael !

Je crois que vous utiliser le [Web Messenger](https://github.com/smooch/smooch-js) et non notre [SDK iOS](https://github.com/smooch/smooch-ios).

Malheureusement, Il n'est pas possible de configurer de le "from" dans les réponses au client envoyé par email en ce moment. Je vais ajouter votre demande au back log.

**Comment by ganael** [comment]
Bonjour ! Ce serait possible en utilisant SDK iOS ? 
Je vois pas trop la différence, suis pas super expert héhé.

**Comment by jpjoyal** [comment]
Ce n'est pas possible via iOS non plus. Cette partie est controlé sur nos serveur seulement.

**Comment by ganael** [comment]
Ok, ce serait top si on pouvait traduire plus d'éléments dans Web Messenger, pour rendre l'expérience vraiment seamless pour les clients français, qui connaissent pas toujours des mots comme "from" ou autres, même si cela peut sembler basique. Dans le même registre, on ne peut pas traduire le "Message posté via Smooch" en bas du live chat. Ce sont des détails, mais je me dis que ce n'est pas forcément difficile de les rendre paramétrables par les clients (comme les autres traductions en fait) mais je me trompe peut-être !

**Comment by jpjoyal** [comment]
Merci de la suggestion. C'est noté.
