### ISSUE TITLE
Done Button in Navigation Bar

### ISSUE THREAD

**Issue by janweinkauff** [smooch/smooch-ios#150]
Releaes 5.6.2  contains following change:
> Added a Done button to the right of the nav bar to dismiss the keyboard when the chat view is contained

I'm using the Smooch conversation view controller as root view controller of an UINavigationController. If I start enter text no done button shows up in the right bar button item.

Could you explain under which conditions the setup of the done button works?

**Comment by wmora** [comment]
The button is displayed when it is being presented in a `UITabBarController`. If the view is presented as a root view in a `UINavigationController` like you described the behavior is the same as before

**Comment by janweinkauff** [comment]
Works great, thanks! 👍
