### ISSUE TITLE
Confirmation for "Use Last Photo Taken"

### ISSUE THREAD

**Issue by janweinkauff** [smooch/smooch-ios#152]
Please, add alert/dialog or delegate call before sending last photo taken to confirm sending.

The alert/dialog should display the photo so the user can check if it is the right photo.

**Comment by jpjoyal** [comment]
Thanks @janweinkauff. Completely understand the ask. I've added the suggestion in our backlog.

**Comment by warpling** [comment]
I get a lot of complaints about this feature too fwiw! …too many close call risque photos followed by "OMG PLZ IGNORE THAT <50 new line characters>"…

**Comment by wmora** [comment]
This feature was released in version [6.2.1](https://github.com/smooch/smooch-ios/releases/tag/6.2.1)
