### ISSUE TITLE
Map and direction sent by bussiness integration open google maps as lat and long not location name

### ISSUE THREAD

**Issue by abadikaka** [smooch/smooch-ios#153]
Hi.. i have question
I get a location from my bussiness integration (Map & Direction) by name. and then when i click on the maps and direction it open google maps but it show as lat and long not a location name..
can we like pointed out it as location name instead of only lat long ?

example  i sent location name : Aloft Hotel
when i open google maps it shown as lat and long instead of the Aloft hotel name (ios) but on android become null (unnamed location)..
is there anything i can do from native layer ?

**Comment by mspensieri** [comment]
Hey, I'm not sure I understand your question. Could you include some sample payloads or screenshots of what you're describing?

> example i sent location name : Aloft Hotel

Where are you sending this from? Our SDKs don't provide a map view to select a location - we just send the current coordinates of the user. Not sure what you mean by sending a location name

> on android become null (unnamed location)..

Where are you seeing this string "unnamed location" ?

**Comment by abadikaka** [comment]
Ok @mspensieri  so here i attach 4 files


0. Smooch chat windows
![18155465_10206919355141085_144153115_n](https://cloud.githubusercontent.com/assets/7501729/25348571/d9d563f6-2948-11e7-95b1-a34f8deee439.jpeg)

1. Expected Result after click map and directions (There is Aloft Hotel Name or whatever the place name)
![Uploading 18136159_10206919338660673_2007560878_n.jpeg…]()

2. Result on iOS when i click on the maps and direction (Open Google Map but written Lat Long)
![resultios](https://cloud.githubusercontent.com/assets/7501729/25348431/66200718-2948-11e7-9216-e37add0707d3.jpeg)

3. Result on android (unnamed location)
![resultandroid](https://cloud.githubusercontent.com/assets/7501729/25348430/66174d30-2948-11e7-8307-deef3ba987b2.jpeg)

**Comment by abadikaka** [comment]
@mspensieri yes, i sent location from our bussiness integration.. 
but can we once open the maps and direction will opened up the location name instead of lat long ? bcs seems it is on native smooch sdk layer button of maps and direction..

**Comment by mspensieri** [comment]
Okay so it looks like you're sending a [Link Button](https://docs.smooch.io/guide/structured-messages/#link-buttons) with a Google Maps link as the `uri`? If this is the case then Smooch just sends the `uri` directly to the operating system to open (on iOS we call `[[UIApplication sharedApplication] openURL:yourUri];`). If the link is opened correctly then I would assume that it was malformed by your business system integration.

Do you have a specific user I can take a look at to see what one of those link buttons looks like?

**Comment by abadikaka** [comment]
Okay @mspensieri, i will ask the back end team first what kind of button they sent to me. .
 what do u mean by specific user ? What kind of use whih u wanna take a look ?
and for make it open as a name, what bussiness int need to sent to mobile ?

**Comment by mspensieri** [comment]
I mean if you know the `smoochId` of a specific user who has received one of these buttons, I could check in the conversation history to see what that `uri` looks like.

I'm not sure exactly how google maps links work but I would assume it's the difference between the two links below:

https://www.google.ca/maps/place/Central+Park+Zoo/@40.7681521,-73.9708715,17.39z/data=!4m5!3m4!1s0x0:0x65d72e84d91a3f14!8m2!3d40.7677778!4d-73.9718337
vs 
https://www.google.ca/maps/@40.7679113,-73.9713638,18.39z

**Comment by abadikaka** [comment]
Ah i see. So u can check through my apptoken and userid directly ? I am not sure which userid . But i remember it is 329 for my test userid which i initiate when do Smooch.login() @mspensieri..

**Comment by mspensieri** [comment]
Ok thanks, so looking at the history I see a few actions that look like this:

```
{
    "text" : "Map & Directions",
    "uri" : "https://maps.google.com/?q=29.738772,-95.470858",
    "type" : "link"
}
```

If you open that `uri` in the browser, you'll see that it's just pointing to a location (latitude & longitude) and not an actual named place. The issue seems to be with the url itself rather than Smooch, so I'll close this issue.

Good luck :)

**Comment by abadikaka** [comment]
Ok thanks !
