### ISSUE TITLE
Cant set UINavigationBar.appearance().topItem?.title dynamically ?

### ISSUE THREAD

**Issue by abadikaka** [smooch/smooch-ios#155]
Hi.. i try to change the navigation bar title dynamically like this one

`UINavigationBar.appearance().topItem?.title = "some title"`

but it is not changing,
i know that Smooch using custom localization and i also try changing the key on localization like this one

`"Messages" = "%@"`

and try access it using localization code in swift, but then i need place those text somewhere in the navbar title. but nothing happened
then i try print the `UINavigationBar.appearance().topItem?` , it print nil. so i want to ask, actually where is the nav item for the Done and title text itself ? Bcs i would like replacing the Message title with dynamic parameter..

this is what i want to change --> the message title with something dynamic

![screen shot 2017-05-03 at 2 10 18 pm](https://cloud.githubusercontent.com/assets/7501729/25650923/5d467226-300a-11e7-85d1-fb97aa89f2ee.png)

**Comment by spasiu** [comment]
@abadikaka We don't currently have a way to do this. The solution would be to build your own UI component.

**Comment by abadikaka** [comment]
ok thanks , @spasiu . so all of the post message function, receive etc will be handled by our own component right ?

**Comment by spasiu** [comment]
@abadikaka Basically, you can call all of the Smooch SDK methods and delegates, but build your own view.

**Comment by abadikaka** [comment]
@spasiu yeah, okay thanks, basically we just need the title to be dynamic, kinda too much work around if build whole own UI. thank you so much for the reply

**Comment by Voidozzer** [comment]
For anyone looking for solution this small hack works perfectly
```
CATransaction.begin()
CATransaction.setCompletionBlock {
    if let topController = UIApplication.topViewController() {
         topController.navigationItem.title = "Whatever you want"
    }
}
Smooch.show()
CATransaction.commit()
```
Of course you'll need extension for UIApplication with `topViewController` function but it can easily be found on Google.

**Comment by abadikaka** [comment]
@Voidozzer i would avoid that way and use @spasiu  suggestion instead. Using CATransaction is too expensive in iOS way especially when rendering the UI. it might be work but i would prefer the official way

**Comment by shehanGuruge** [comment]
Hey there Is it possible to even to change the title of that view "Messages" to a different static title like "Support" or something in both ios and android?
