### ISSUE TITLE
Smooch chat widget scroll listener / Touch listener

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#156]
I want the callback/Delegate for Smooch chat window scroll listener.
or is there any thing I can detect the touch on chat window. I need to do something on that event.

Anything like

```
override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
}

override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {
}

override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
}
```

or 

```
func scrollViewDidScroll(_ scrollView: UIScrollView) {
}

```

**Comment by wmora** [comment]
we don't provide any callbacks for our UI atm, the only way for you to do this would be to build your own UI

**Comment by qadirsuh** [comment]
I think it will be very easy to support this feature. isn't? I don't want to make my whole logic change because of this enhancement. can you please launch this in you next smooch version update?
