### ISSUE TITLE
"STRINGNOTFOUND" 

### ISSUE THREAD

**Issue by FreudGit** [smooch/smooch-ios#159]
Hi

From simulator

When app\simulator are launch from xCode:
When I load (.show) from the sim, I see "STRINGNOTFOUND" almost everywhere.

When app are launch from simulator(without xcode):
When I load (.show) from the sim, I see all text element ok.

Any idea?

**Comment by mspensieri** [comment]
Hmm can't say I've ever seen this happen before. To confirm, do you see `STRINGNOTFOUND` in caps, or `StringNotFound` in camel case?
