### ISSUE TITLE
Carthage install has downloaded for 427MB!!!! 😱

### ISSUE THREAD

**Issue by TofPlay** [smooch/smooch-ios#160]
Hi,
When I installed (`carthage update`) your component with Carthage It did not take the zip version. Instead he made a git clone of your repository and It has downloaded for 427MB!!!! 😱 Not the 6.21MB of your zip file.
```
$ # To check carthage cache
$ du -sh ~/Library/Caches/org.carthage.CarthageKit/dependencies/smooch-ios/
427M	/Users/me/Library/Caches/org.carthage.CarthageKit/dependencies/smooch-ios/
```
If we don't have a fast internet connection it can take a while !!!
Check the doc [Binary only frameworks](https://github.com/Carthage/Carthage/blob/8481919f22b7ee4196f10827209c9d85bf22d469/Documentation/Artifacts.md#binary-only-frameworks). With this option you just have to store a json file on GitHub not the framework it self otherwise each time you upload a new version your repository will continue to grow!!!

**Comment by wmora** [comment]
Thanks for the report, we'll look into what's causing this

**Comment by wmora** [comment]
Sorry for the late response. We've added the binary spec json to the repo. Change the Smooch dependency in your project's `Cartfile` to the following:

```
binary "https://raw.githubusercontent.com/smooch/smooch-ios/master/Smooch.json"
```
