### ISSUE TITLE
We are connected or not?

### ISSUE THREAD

**Issue by TofPlay** [smooch/smooch-ios#161]
Hi,
Here a pseudo code of what I'm doing to initialized the chat:
```swift
// Swift code
Smooch.initWith(SKTSettings(appToken: "<my app token>")
if let lCurrent = SKTUser.current() {
   lCurrent.firstName = lFirstName
   lCurrent.lastName = lLastName
   lCurrent.email = lEmail
  Smooch.show()
}
```
`lFirstName`, `lLastName` and `lEmail` are variables initialized with the user application info. 
I don't need to register users on Smooch so I don't need to use `login` API. But the support needs to know with which user they are discussing.
But when I set the user info the chat displayed the message "Could not connect to server". This gives the impression that we are not connected. Since there are no other messages afterwards we do not know if the chat is finally connected or it still not connected.

**Comment by mspensieri** [comment]
The `Could not connect to server` message can appear if your app token is invalid, or could not be verified with Smooch servers for some reason (maybe due to a bad network connection?). If initialization fails, you should see a line in the Xcode logs prefixed with `<SMOOCH::ERROR>` that should give an indication of why the failure occurred. Could you check your logs and report back here please?

**Comment by TofPlay** [comment]
I checked the logs and I can not find a message starting with `SMOOCH::ERROR` 
If this can help: the message appears when opening the chat the first time. It remains displayed 1s and disappears

**Comment by mspensieri** [comment]
Oh okay, well if it disappears then it means that the connection succeeded.

If the code you posted in your original comment is correct (`.show` called **directly** after `.initWithSettings`), then this delay is expected. After calling `.initWithSettings`, the SDK performs some async work to determine if your app token is valid or not. During this time, the `Could not connect to server` banner can be shown.

Are you not calling `.initWithSettings` in your `applicationDidFinishLaunchingWithOptions` callback?

**Comment by TofPlay** [comment]
> Are you not calling .initWithSettings in your applicationDidFinishLaunchingWithOptions callback

No because I have already a lot of stuff to initialize when the application is launch. The chat is only need when the user click on an option in the menu. I just initialize the chat when it's really used.

**Comment by mspensieri** [comment]
In that case I would consider this working as intended. For the first ~1 second after `.show`, the connection has not yet been confirmed (since it's still connecting), then when the connection is established, the error disappears

**Comment by TofPlay** [comment]
For the user have this message is not clear
They will think that the connection is still not established
Suggestion 1: Display this message after 2s or 3s
Suggestion 2: After displayed `Could not connect to server` when the connection is established displayed an other message like `Connection established`

**Comment by mspensieri** [comment]
Thanks for the feedback, I'll mark this as an enhancement request and pass your suggestion to the team!

**Comment by mspensieri** [comment]
I believe this was addressed at some point, but I'm not sure which version 😅 . Please reopen if you still have issues with the latest version
