### ISSUE TITLE
Warning with Xcode 9

### ISSUE THREAD

**Issue by genadyo** [smooch/smooch-ios#162]
<img width="538" alt="screen shot 2017-08-02 at 11 34 52 pm" src="https://user-images.githubusercontent.com/2101043/28893732-37446862-77db-11e7-9843-406215911638.png">

**Comment by wmora** [comment]
Thanks! We've already identified warnings and changes for XCode 9. We're prioritizing it internally and will be included in a future release

**Comment by genadyo** [comment]
Thank you

**Comment by mspensieri** [comment]
This should be fixed in [v5.8.2](https://github.com/smooch/smooch-ios/releases/tag/5.8.2)

**Comment by genadyo** [comment]
Thank you :)
