### ISSUE TITLE
Date Header sometimes not showing up properly in iOS (v. 5.6.7)

### ISSUE THREAD

**Issue by abadikaka** [smooch/smooch-ios#163]
Hi guys, after 5 months using Smooch, i just found this strange issues...
not sure if this old issue or i need to upgrade..
currently i am using 5.6.7 version in ios
but i found that sometimes the date not showing properly in iOS, opposite in android that they can show correctly...

Here i put attachment in same conversation using different platform and i put some comment on the picture

# ANDROID
![android_1](https://user-images.githubusercontent.com/7501729/29401427-560a3b60-835b-11e7-957d-182eb7564279.png)
![android_2](https://user-images.githubusercontent.com/7501729/29401426-55fb285a-835b-11e7-8a7b-09bc076a3138.png)

# IOS
![ios_1](https://user-images.githubusercontent.com/7501729/29401425-55f8a21a-835b-11e7-98ca-57f35abffd94.png)
![ios_2](https://user-images.githubusercontent.com/7501729/29401424-55ef4f44-835b-11e7-8878-6c59e4d5046b.png)

is this because i am using 5.6.7 version or known issues ?
Thanks..

@mspensieri @wmora

**Comment by mspensieri** [comment]
Looks like the algorithm for when to show the date is different in iOS and Android. On iOS the timestamp will only show when two adjacent messages have more than 24hrs in between them. So theoretically if you sent a message every 23 hours for 1 month you would never see the timestamp. I'm not 100% sure what the criteria is in Android, but it looks like it's grouping by calendar days (based on your screenshot).

I've filed an improvement to revisit this algorithm with your feedback

**Comment by abadikaka** [comment]
Okay thanks @mspensieri for the explanation.

Actually i also found something else regarding date in iOS. In Thailand, my thai friend iphone timezone is set into Thai Year (which is 2560 something not 2017). 
This one cause something with last photos taken inside smooch chat window (it make when i use a camera to take photo and send it, it always sent last photo not current photo that i just take with the camera). 
I will recheck that issue if i remember the flow of it again later in here, hope it helps.

**Comment by wmora** [comment]
This was fixed in [v6.0.2](https://github.com/smooch/smooch-ios/releases/tag/6.0.2)
