### ISSUE TITLE
issue with smooch <> frontApp integration, messages not recieved on FrontApp

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#165]
A couple of days ago I got an issue, this may not be smooch issue or it may be. let me define the whole scenario.
I have integrated smooch-iOS sdk in my iOS app and obviously  as my messaging channel, and I have Configured Slack and  frontApp as my business channel (Receiving end) with smooch dashboard.
Its working flawlessly, a couple of days ago I tried to login smooch (using smooch-iOS sdk) with userId containing heart shaped smiley icon (unicode character) something like "Dear,1596090Mike_💖_Fred"
It logged in successfully but when our guest (user) started chat via smooch-ios chat widget the messages only received on slack but not on my frontApp, This was the actual issue. 
what is the root cause? is it smooch login issue or frontApp issue,

Here are some tests I have done so for to reproduce this issue. 
I tried to login smooch with userid having Chinese, German and Urdu Characters too and it worked flawlessly (i.e messages received on both channels i.e slack and frontApp) even I tried with a different smiley icon i.e ❤️ and it worked too.
only this heart 💖 is creating the problem. You can reproduce this too at your side. I am curios to know this, whats special in this heart. :)

Here is my swift iOS code to initSmooch

```
func initSmooch(userID:String, guest_name:String){
        if (UserDefaultsManager().getFirebaseConfiguration()){
                        
            if(self.jamesAppSettings?.homeSupportConfig?.useSmoochProd)!{
                smoochSettings = SKTSettings(appToken: AppUtils.smooch_app_token_live)
            }else{
                smoochSettings = SKTSettings(appToken: AppUtils.smooch_app_token_staging)
            }   
        }
        smoochSettings?.userId = userID // To save userID based conversations smooch widget        
        Smooch.initWith(smoochSettings!);
       SKTUser.current()?.firstName =  guest_name;
        }
    }
```

**Comment by mspensieri** [comment]
Hmm well if the message is making it correctly to Slack, then I don't think this is an issue with the iOS SDK. It could be an issue with webhooks, or maybe with Front's integration? You can check the Logs tab on app.smooch.io to see where the message goes after it is sent from iOS - you should be able to see if Front is returning an error or not.

GitHub issues on this repository are reserved for issues directly related to the iOS SDK, so I'll close this issue, but feel free to send your question to help@smooch.io and someone can help you there!

**Comment by qadirsuh** [comment]
I found the logs. here is a snapshot. is there any thing that states that messages are not delivering to FrontApp but delivering to slack. ?

![image](https://user-images.githubusercontent.com/14326497/30414009-e8d28dae-993a-11e7-81d6-963c31e6200c.png)

**Comment by qadirsuh** [comment]
Fred Comments via email:

Hey Qadir! 

Thanks for reaching out to the team. I'm seeing that you've opened an issue on Github and got some answers there from our team. 

From the log screenshot you sent us, we can see that we're successfully delivering the webhook to Front. That leads us to the conclusion that the issue is likely coming from Front. Would you mind reporting it the them directly? 

Keep us updated, 

Fred
