### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by genadyo** [smooch/smooch-ios#167]
![simulator screen shot - iphone x - 2017-09-19 at 19 47 54](https://user-images.githubusercontent.com/2101043/30604419-7793b482-9d73-11e7-86ef-dc34f2758013.png)

**Comment by wmora** [comment]
Thanks! We've already identified missing adjustments to fully support iPhone X. We're prioritizing it internally and will be included in a future release

**Comment by wmora** [comment]
Fixed in [v6.1.0](https://github.com/smooch/smooch-ios/releases/tag/6.1.0)
