### ISSUE TITLE
How does one generate a JWT?

### ISSUE THREAD

**Issue by warpling** [smooch/smooch-ios#168]
This is a foreign concept and the docs leave much to be desired for an iOS developer that isn't familiar with the concept. Is this just a different API key/secret that needs to be generated once?

**Comment by mspensieri** [comment]
It depends what you're using the JWT for. For server to server calls, you can generate a single JWT to use on your server and it will work forever. 

However, in the context of the iOS SDK, chances are you're wanting to sign JWTs to use the `login` API, right? You can read through the [multi-client users](https://docs.smooch.io/guide/multi-client-users/) section of our documentation for an overview on how assigning `userId`s works, and see the [authenticating users](https://docs.smooch.io/guide/authenticating-users/) section for a simple guide to generate user-scoped JWTs on node.js. 

> Is this just a different API key/secret that needs to be generated once?

For JWTs that are used on iOS (or any Smooch SDK, for that matter), each user that is logged in will need their own unique JWT with the user's `userId` embedded in it. This grants the user access to their own data, and nothing else. The JWT should be generated whenever the user completes a login flow against your own server (after your server has proven their identity).

For more in-depth information on how to generate a JWT that Smooch accepts, see the [Authorization](https://docs.smooch.io/rest/#authorization) and [Authentication](https://docs.smooch.io/rest/#authentication) sections of the REST API docs. If your server is not written in node.js, we also have code samples in [python](https://github.com/smooch/smooch-python#step-2-generate-the-jwt), [java](https://github.com/smooch/smooch-java#step-2-generate-the-jwt), or [ruby](https://github.com/smooch/smooch-ruby#step-2-generate-the-jwt).

**Comment by warpling** [comment]
Thanks @mspensieri.

I don't use a server for my app and that was one of the beauties of Smooch. (I essentially use to communicate with my beta testers and don't use any advanced features.) Sounds like I need to setup a server to authenticate users in order to continue using Smooch?

**Comment by mspensieri** [comment]
That's correct
