### ISSUE TITLE
iOS 11 Done Button

### ISSUE THREAD

**Issue by goktugyil** [smooch/smooch-ios#169]
My users can't press the Done Button in the new iOS version. They have to close and open the app to get back to the last ViewController. 

http://prntscr.com/gr3i8i

**Comment by mspensieri** [comment]
This was supposed to have been fixed in [v5.8.2](https://github.com/smooch/smooch-ios/releases/tag/5.8.2), which version are you using?

**Comment by goktugyil** [comment]
I couldn't find my version. Smooch.version returned 0.

I updated pods and its working fine now, thanks
