### ISSUE TITLE
Provided credentials were invalid

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#171]
I am trying to login a userID with JWT. I am getting this log. 
`Provided credentials were invalid. Either your app id, JWT, or both are incorrect.`

How to debug this?

Here is my iOS swift4 code for initSmooch()

      `func initSmooch(userID:String, guest_name:String){
        
        if (UserDefaultsManager().getFirebaseConfiguration()){
            
            print("useSmoochProd \(String(describing: self.jamesAppSettings?.homeSupportConfig?.useSmoochProd))")
            
            if(self.jamesAppSettings?.homeSupportConfig?.useSmoochProd)!{
                smoochSettings = SKTSettings(appId: AppUtils.smooch_app_id_live)
            }else{
                smoochSettings = SKTSettings(appId: AppUtils.smooch_app_id_staging)
            }
        }
        
        Smooch.initWith(smoochSettings!) { (error: Error?, userInfo: [AnyHashable : Any]?) in
            
            // Your code after init is complete
            print("initWith", "called");
            
            if(error != nil){
                print("error smooch init", error!.localizedDescription); // error smooch init Bad status code : 401 unauthorized
            }
            
            self.smoochLogIn(userID:userID, guest_name:guest_name)
        }
    }`

I am getting this too here 
`Provided credentials were invalid. Either your app id, JWT, or both are incorrect.`

here is my smoochLogin() code

      `func smoochLogIn(userID:String, guest_name:String){
        var jwt:String = "";
        
        if(self.jamesAppSettings?.homeSupportConfig?.useSmoochProd)!{
            jwt = JWT.encode(claims: ["scope": "app"], algorithm: .hs256(AppUtils.smooch_key_id_live.data(using: .utf8)!))
        }else{
            jwt = JWT.encode(claims: ["scope": "app"], algorithm: .hs256(AppUtils.smooch_key_id_staging.data(using: .utf8)!))
        }
        
        Smooch.login(userID, jwt: jwt) { ( error:Error? , userInfo:[AnyHashable : Any]?) in

            // Your code after login is complete
            
            let fullNameArr = guest_name.characters.split{$0 == " "}.map(String.init)
            
            if(fullNameArr.count > 1){
                
                SKTUser.current()?.firstName = fullNameArr[0]
                SKTUser.current()?.lastName = fullNameArr[1]
                
            }else{
                
                SKTUser.current()?.firstName = fullNameArr[0]
                SKTUser.current()?.lastName = fullNameArr[0]
                
                let fullNameArr = guest_name.characters.split{$0 == "-"}.map(String.init)
                
                if(fullNameArr.count > 1){
                    
                    SKTUser.current()?.firstName = fullNameArr[0]
                    SKTUser.current()?.lastName = fullNameArr[1]
                }
            }
        }
    }`

I am using the following JWT lib for swift
https://github.com/kylef/JSONWebToken.swift

**Comment by mspensieri** [comment]
The JWT you are providing is using scope `app`, however the SDK requires a JWT of scope `appUser`. See [authenticating users](https://docs.smooch.io/guide/authenticating-users/) or [this StackOverflow question](https://stackoverflow.com/questions/46570529/unable-to-login-user-id-to-web-messenger-invalid-scope/46570680) for more information. It also looks like you are not passing the `keyId` header in your JWT.

Also it's strongly discouraged to sign JWTs in your application (i.e. in Swift), as it implies distributing your app secret key with your mobile application, essentially granting all of your users access to your entire Smooch app. JWTs should be signed on your server and passed down to the client device.

**Comment by qadirsuh** [comment]
I have commented out the login code for now, I am trying to initSmooch() only. here is my current code. 

`func initSmooch(userID:String, guest_name:String){
    
    if (UserDefaultsManager().getFirebaseConfiguration()){
        
        if(self.jamesAppSettings?.homeSupportConfig?.useSmoochProd)!{
            smoochSettings = SKTSettings(appId: AppUtils.smooch_app_id_live)
        }else{
            smoochSettings = SKTSettings(appId: AppUtils.smooch_app_id_staging)
        }
    }
    
    Smooch.initWith(smoochSettings!) { (error: Error?, userInfo: [AnyHashable : Any]?) in
        
        // Your code after init is complete
        print("initWith", "called");
        
        if(error != nil){
            print("error smooch init", error!.localizedDescription); // error smooch init Bad status code : 401 unauthorized
        }
        
        //self.smoochLogIn(userID:userID, guest_name:guest_name)
    }
}`

Login is my next step. I am stuck on initSmooch(), I am getting this. 
`error smooch init Bad status code : 401 unauthorized`

**Comment by mspensieri** [comment]
Init is failing because your stored JWT is incorrect. When calling `Smooch.login`, the SDK will cache the passed `userId` and `jwt` on disk to use on subsequent app startups. Until you explicitly logout using `Smooch.logout`, or switch users using a new call to `Smooch.login`, the same credentials will be used. This is why `init` is failing even if you comment out the call to `login`; the user is _already_ logged in with incorrect credentials

**Comment by mspensieri** [comment]
On the other hand, I can see how this behaviour can be problematic. I've filed an improvement on our side to not store the credentials on disk unless the login was successful

**Comment by qadirsuh** [comment]
Ahh.. I deleted the app and re-installed it on my iPad, I did't get any error on initSmooch() now.
Now next step is to successfully login the user (and obviously this is going to save the valid jwt credentials.) 

So I have changed my login method to something like this. 

     `func smoochLogIn(userID:String, guest_name:String){
        
        print("smoochLogIn", "called")
        
        var jwt:String = "";
        
        if(self.jamesAppSettings?.homeSupportConfig?.useSmoochProd)!{
            jwt = JWT.encode(claims: ["appUser": userID], algorithm: .hs256(AppUtils.smooch_secret_live.data(using: .utf8)!))
        }else{
            jwt = JWT.encode(claims: ["appUser": userID], algorithm: .hs256(AppUtils.smooch_secret_staging.data(using: .utf8)!))
        }
        
        print("jwt", jwt);
        
        Smooch.login(userID, jwt: jwt) { ( error:Error? , userInfo:[AnyHashable : Any]?) in

            // Your code after login is complete
            
            if(error != nil){
                print("error smooch login error != nil", error!.localizedDescription);
            }
            
            let fullNameArr = guest_name.characters.split{$0 == " "}.map(String.init)
            
            if(fullNameArr.count > 1){
                
                SKTUser.current()?.firstName = fullNameArr[0]
                SKTUser.current()?.lastName = fullNameArr[1]
                
            }else{
                
                SKTUser.current()?.firstName = fullNameArr[0]
                SKTUser.current()?.lastName = fullNameArr[0]
                
                let fullNameArr = guest_name.characters.split{$0 == "-"}.map(String.init)
                
                if(fullNameArr.count > 1){
                    
                    SKTUser.current()?.firstName = fullNameArr[0]
                    SKTUser.current()?.lastName = fullNameArr[1]
                }
            }
        }
    }`

Note: see I have passed the scope as appUser.

above you have mentioned I have to pass the keyid in header. can you guid me on this. 
I am using https://github.com/kylef/JSONWebToken.swift library to generate the jwt.

**Comment by mspensieri** [comment]
See my answer above:

> Also it's strongly discouraged to sign JWTs in your application (i.e. in Swift), as it implies distributing your app secret key with your mobile application, essentially granting all of your users access to your entire Smooch app. JWTs should be signed on your server and passed down to the client device.

I won't help you work with the Swift lib as you should not be signing JWTs in your mobile app. We provide code samples in many server languages, such as [node.js](https://docs.smooch.io/guide/authenticating-users/), [python](https://github.com/smooch/smooch-python#step-2-generate-the-jwt), [java](https://github.com/smooch/smooch-java#step-2-generate-the-jwt), or [ruby](https://github.com/smooch/smooch-ruby#step-2-generate-the-jwt).

**Comment by qadirsuh** [comment]
Thanks for this. 
Okay, I have moved my code to server now, 

here is my code. 

```
'use strict';

var jwt = require('jsonwebtoken');

var smooch_app_id_staging = "XXXXXXXX";
var smooch_app_token_staging = "XXXXXX";
var smooch_key_id_staging = "XXXXXXXXXXX";
var smooch_secret_staging = "XXXXXXXX";

var smooch_app_id_live = "XXXXXXXX";
var smooch_app_token_live = "XXXXXX";
var smooch_key_id_live = "XXXXXXXXX";
var smooch_secret_live = "XXXXXXXXX";


class JwtGenerator {

    getJwt(useSmoochPro, userId, callBack) {

        var KEY_ID = '';
        var SECRET = '';

        if (useSmoochPro == true) {
            KEY_ID = smooch_key_id_live;
            SECRET = smooch_secret_live;
        } else {
            KEY_ID = smooch_key_id_staging;
            SECRET = smooch_secret_staging;
        }

        console.log(KEY_ID);
        console.log(SECRET);

        callBack(this.getJwtMain(userId, SECRET, KEY_ID));

    }

    getJwtMain(userId, SECRET, KEY_ID) {

        return jwt.sign({
                scope: 'appUser',
                userId: userId
            },
            SECRET,
            {
                header: {
                    alg: 'HS256',
                    typ: 'JWT',
                    kid: KEY_ID
                }
            });
    }

}

module.exports = JwtGenerator
```

I am calling this webservice now from my iPad, it return me the jwt and I am loging into using that jwt in my iOS app. but still I m getting the same error. here is the log.

```
<SMOOCH::ERROR> Provided credentials were invalid. Either your app id, JWT, or both are incorrect.
error smooch login error => Bad status code : 401 unauthorized
```
here is my ios CurrentUser log **Note: SmoochID is null.**

```
USER ID("837988Le_Bijou_Guestess")
SMOOCH ID nil
CURRENT USER FIRST NAME:("Dear")
CURRENT USER LASTNAME:("Guest")
```

**Comment by mspensieri** [comment]
1. You can use the form at [jwt.io](https://jwt.io) to inspect your JWT and make sure it contains all the required fields, and validate that the signature is correct.
2. Make sure the key/secret you are using matches the app id supplied in `init`
3. If you inspect the `userInfo` dictionary in the completion handler of the `login` or `init` callbacks, you can see more information about the error, and why the call was rejected

**Comment by qadirsuh** [comment]
Here is my smooch login logs, 

`error smooch login error != nil Bad status code : 401 unauthorized
userInfo login -------------
userInfo isEmpty Optional(false)
userInfo keys Optional(Swift.Dictionary<Swift.AnyHashable, Any>.Keys(_variantBuffer: Swift._VariantDictionaryBuffer<Swift.AnyHashable, Any>.native(Swift._NativeDictionaryBuffer<Swift.AnyHashable, Any>(_storage: {
    SKTErrorCodeIdentifier = "invalid_auth";
    SKTErrorDescriptionIdentifier = "Invalid JWT header. Missing key id (kid)";
    SKTStatusCodeIdentifier = 401;
}))))
userInfo values Optional(Swift.Dictionary<Swift.AnyHashable, Any>.Values(_variantBuffer: Swift._VariantDictionaryBuffer<Swift.AnyHashable, Any>.native(Swift._NativeDictionaryBuffer<Swift.AnyHashable, Any>(_storage: {
    SKTErrorCodeIdentifier = "invalid_auth";
    SKTErrorDescriptionIdentifier = "Invalid JWT header. Missing key id (kid)";
    SKTStatusCodeIdentifier = 401;
}))))
userInfo login -------------`

here is the code producing above log
` if(userInfo != nil){
                    
                    print("userInfo login", "-------------");
                    
                    print("userInfo isEmpty", userInfo?.isEmpty);
                    print("userInfo keys", userInfo?.keys);
                    print("userInfo values", userInfo?.values);
                    
                    print("userInfo login", "-------------");
                }`

I think we are almost near, to debug this :)

**Comment by qadirsuh** [comment]
update 2.
I have verified the jwt is verified from jwt.io too and looks valid.

![image](https://user-images.githubusercontent.com/14326497/31483783-4b82459e-af47-11e7-97ce-d703448f88d3.png)

**Comment by qadirsuh** [comment]
@mspensieri  please confirm me that kid is the same key Id we get from smooch dashboard. 
i.e see Image screen shot below

http://prntscr.com/gwdwqt

**Comment by qadirsuh** [comment]
I have found the issue. 

This issue is in your nodeJs jwt generating code mentioned here
https://docs.smooch.io/guide/authenticating-users/

![image](https://user-images.githubusercontent.com/14326497/31493140-5ba708ae-af67-11e7-9934-9e10e3b46cd6.png)

**Comment by mspensieri** [comment]
The `header` option is correct if you are using v6.0.0+ of the `jsonwebtoken` library. In old versions (< v6.0.0, i.e. older than April 26, 2016), the option used to be called `headers`. This is mentioned in our documentation and is visible in your screenshot.

 See [their documentation](https://github.com/auth0/node-jsonwebtoken) for usage of the `sign` function and accepted options

**Comment by qadirsuh** [comment]
Thanks for this :) 👍 
I can successfully login into smooch using the web-version. using above backend code. but when I am trying to login via ios app, I am getting a different error now.

```
    SKTErrorCodeIdentifier = "bad_request";
    SKTErrorDescriptionIdentifier = "AppId in path does not match supplied credentials";
    SKTStatusCodeIdentifier = 400;
```
hope you can guid us through this.

**Comment by srijan12345** [comment]
Provided credentials were invalid. Either your app token, JWT, or both are incorrect.

Getting this error with valid Smooch app id..can u please let me know the proper solution of this issue

**Comment by qadirsuh** [comment]
Please uninstall the app every time you get this error, and try again with new app install. JWT are saved in local device storage and used in every request. make sure to remove the app and re-install it before testing it. its real pain.

**Comment by mspensieri** [comment]
@srijan12345 your error message mentions `app token`, which means you are using an SDK version < 6.0.0, but you also said you are supplying an `app id`, which is not the same thing.

App token is used on 5.x and lower, App ID is used on 6.x. Please make sure you are using the correct value for your SDK version, or upgrade to the latest version and supply the App ID you see in the Smooch dashboard

**Comment by dsrijan** [comment]
Yes @mspensieri , I was using through cocoapods. After updating pods it get resolved. Thanks. A lot changes coming frequently in your sdk. I think, u guyz should make releases after some period of time atleast in customer applications.

**Comment by mspensieri** [comment]
@dsrijan you can pin a specific version in Cocoapods if you don't want to automatically get updates. Change `pod 'Smooch'` in your Podfile to `pod 'Smooch', '6.3.2'` or whatever version number you'd like to use.

**Comment by AErmek** [comment]
> Init is failing because your stored JWT is incorrect. When calling `Smooch.login`, the SDK will cache the passed `userId` and `jwt` on disk to use on subsequent app startups. Until you explicitly logout using `Smooch.logout`, or switch users using a new call to `Smooch.login`, the same credentials will be used. This is why `init` is failing even if you comment out the call to `login`; the user is _already_ logged in with incorrect credentials

Hello,
What about jwtTokens with expiration?

**Comment by mspensieri** [comment]
@AErmek See https://docs.smooch.io/guide/native-ios-sdk/#login-with-externalid-and-jwt, specifically the section titled "Authentication delegate"
