### ISSUE TITLE
Bad status code : 401 unauthorized

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#172]
I am trying to initSmooch() with my smooch appId, I am getting this error. 
`Bad status code : 401 unauthorized`

here is my code

     `func initSmooch(userID:String, guest_name:String){
        
        if (UserDefaultsManager().getFirebaseConfiguration()){
            
            // Check which smooch App to use live/staging
            if(self.jamesAppSettings?.homeSupportConfig?.useSmoochProd)!{

                Smooch.initWith(SKTSettings(appId: AppUtils.smooch_app_id_live)) { (error: Error?, userInfo: [AnyHashable : Any]?) in
                    
                    print("initWith", "smooch_app_id_live");
                    
                    if(error != nil){
                        print("error smooch init", error!.localizedDescription); // Bad status code : 401 unauthorized
                    }
                }

            }else{

                Smooch.initWith(SKTSettings(appId: AppUtils.smooch_app_id_staging)) { (error: Error?, userInfo: [AnyHashable : Any]?) in
                    
                    print("initWith", "smooch_app_id_staging");
                    
                    if(error != nil){
                        print("error smooch init", error!.localizedDescription); // Bad status code : 401 unauthorized
                    }
                }
            }
        }
    }`

here is the complete log

`2017-10-11 15:20:43.484559+0500 jamesAppV2[7581:173446] Could not successfully update network info during initialization.
2017-10-11 15:20:44.455087+0500 jamesAppV2[7581:173449] <SMOOCH::ERROR> Provided credentials were invalid. Either your app id, JWT, or both are incorrect.
initWith smooch_app_id_live
error smooch init Bad status code : 401 unauthorized
`

**Comment by mspensieri** [comment]
Dup of #171
