### ISSUE TITLE
auto logout / Jwt expires ?

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#175]
I have doubt that, my app is executing the Smooch.logout() automatically after 1h (may be 2h)
is this actually happens behind the scenes?  or may be jwt expires or anything like that. may be I am wrong. but I need to be clear about this question.

```
Smooch.logout { (error:Error? , userInfo:[AnyHashable : Any]?) in

})
```

**Comment by wmora** [comment]
We don't run any type of background task that calls `logout()`. The only way you will be logged out of the SDK is if you either log in with a new user (logout for the previous user is implicit in this case) or if you explicitly call `Smooch.logout`
