### ISSUE TITLE
Switching between two smooch Apps in single iOS App

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#176]
I am using two instances of smooch App in my single iOS app. One is staging and other one is for live.
Is there any way to switch between the apps. 

I know I can initiate the smooch app one time. smooch not allows multiple app initiates. 

I need to switch in between the apps both apps, I was working previously in < 6.0.XX version.
but now after jwt in login, its creating the problem. 

Here is what I am facing.
Installed the app in a new device, then initiated my staging app and logged in with a certain userId , works great. then I changed the smooch app to live `(i.e SKTSettings(appId: AppUtils.smooch_app_id_live))` Now I get the issue. I get `Bad request 400` on smooch init and on login too. 

But when I deleted the App and reinstalled its start working fine. I am sure the JWT is some how creating the issue.

I need some workaround for this. please

**Comment by mspensieri** [comment]
To switch apps at runtime, call `Smooch.destroy` and then call `initWithSettings` again with the different ID. JWTs are stored on disk per app ID, so a JWT for one app should not be affecting the other. Just make sure that when you call `login`, that the JWT you supply matches the app ID that you've initialized with.

**Comment by qadirsuh** [comment]
I am going to implement this in my app. but Docs says, it shouldn't called manually.

I am sure, this is not going to create any problem

![image](https://user-images.githubusercontent.com/14326497/31885013-8b01d3d2-b808-11e7-9d43-82082da2ce32.png)

**Comment by mspensieri** [comment]
Yes it should not cause any problems, not sure why it has been documented that way

**Comment by qadirsuh** [comment]
I am doing like this now. 

```
// Destory first the already Loged in APP
        Smooch.destroy()
        self.appDelegate.initSmooch(userID: guest_id, guest_name:guest_name, completion: {

})
```

But getting this.
`<SMOOCH::ERROR> Init called more than once, aborting init sequence!`

Am I doing something wrong? I was assuming, I have to call smooch.destroy() and then call initSmooch() again to re-init smooch App. isn't ?

**Comment by mspensieri** [comment]
I'm not sure what your `initSmooch` and `smoochLogIn` methods are doing, but this works for me:

```
[Smooch destroy];
[Smooch initWithSettings:settings completionHandler:^(NSError * error, NSDictionary * userInfo) {
    NSLog(@"Init complete: %@ %@", error, userInfo);
}];
```

Maybe there is something in those functions that is calling `initWithSettings` more than once

**Comment by qadirsuh** [comment]
Ahh! thanks for pointing this out. I was actually called more than once. my bad.
