### ISSUE TITLE
Swizzling is disabled but somehow still happen

### ISSUE THREAD

**Issue by mohammad19991** [smooch/smooch-ios#177]
## Issue 🔧
Swizzling is disabled but the chat screen is still presented when the app launched from Smooch notification and app is not in background (terminated).

## Goal ⚽️
I want to do my own handling for push notifications and I don't want the SDK to handle any received push notifications.

## Implementation 🚧
In `didFinishLaunchingWithOptions` I initialize smooch with below settings:

```swift
 let settings = SKTSettings(appToken: CONST.SMOOCH_APP_TOKEN)
settings.enableAppDelegateSwizzling = false
settings.enableUserNotificationCenterDelegateOverride = false
Smooch.initWith(settings)
```

In `didRegisterForRemoteNotificationsWithDeviceToken` I call: 

```swift
Smooch.setPushToken(deviceToken)
```

###### Manual handling for Smooch notifications in:

```swift
func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)

//and 

func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void)

//I check

if userInfo[SKTPushNotificationIdentifier] != nil {
        self?.processSmoochNotification()
        return
}
```

**Comment by mspensieri** [comment]
Possible dup of #118, see [this comment](https://github.com/smooch/smooch-ios/issues/118#issuecomment-260638778), but I'll reiterate here.

> The `enableAppDelegateSwizzling` flag is not intended to be used to change behaviour, it's intended to be used as a workaround when your application needs to do its own handling on the app delegate methods that Smooch overrides. If you look at the documentation for that method, it actually outlines steps that your app must follow to ensure that remote notifications continue to function correctly.

When an application is launched by a push notification, the notification information is passed via the `launchOptions` dictionary. Smooch subscribes to the `UIApplicationDidFinishLaunchingNotification` to receive this information, so no swizzling is necessary.

To prevent the conversation view from appearing, return `false` in the [`conversation:shouldShowForAction:withInfo:`](https://docs.smooch.io/api/ios/Protocols/SKTConversationDelegate.html#//api/name/conversation:shouldShowForAction:withInfo:) delegate method.

**Comment by mohammad19991** [comment]
@mspensieri we tried this approach, it's not working.

**Comment by Latyntsev** [comment]
We had to implement one more delegate method
```
func conversation(_ conversation: SKTConversation, shouldShowFor action: SKTAction, withInfo info: [AnyHashable : Any]?) -> Bool {
    return false
}
```

now it's working fine.
@mspensieri thanks alot for your help
