### ISSUE TITLE
Two 'Done' buttons are showing in navigation bar.

### ISSUE THREAD

**Issue by himanthmaddi** [smooch/smooch-ios#178]
PFA screenshot of my sample app. As soon as I clicked on textfield another 'Done' button appearing on right side. Then If I do click on any Done button, just textfield resigning. So to go back I need to click two times. Please help me out how to solve this.

![img_5764](https://user-images.githubusercontent.com/19431119/32047616-22b111c2-ba64-11e7-8783-bcc8f0c1956f.png)

**Comment by mspensieri** [comment]
The done button on the right-hand side (to dismiss the keyboard) is only supposed to show when the conversation view is contained in a `UITabBarController`, in which case the button on the left should not be displayed at all. So this is indeed a strange behaviour.

Could you provide a description of your view controller hierarchy when Smooch is displayed? Or even better, if you're able to reproduce the issue in a sample project that would be great.

**Comment by himanthmaddi** [comment]
I will, BTW it's disappeared after deleting the app and run it again.
