### ISSUE TITLE
Smooch Init/Login problem, due to quickly switching in between two smooch Apps

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-ios#180]
I am using two instances of smooch App in my single iOS app. One is staging and other one is for live.

I need to switch in between my apps very quickly sometimes. Actually my iOS app is configured with the firebase (The real time database, it works in realtime with sockets) . I have a flag in my firebase database `useSmoochProd`. 
`useSmoochProd => true mean use Live smooch instance, and vice versa.`

The problem is upon toggling that flag quickly I am getting the Smooch Init/Login problem, 

here is my app logs.

```
    SKTErrorCodeIdentifier = "bad_request";
    SKTErrorDescriptionIdentifier = "AppId in path does not match supplied credentials";
    SKTStatusCodeIdentifier = 400;
```

**Comment by mspensieri** [comment]
Closing as this seems like a developer error. `AppId in path does not match supplied credentials` means the JWT you supplied does not match the app ID passed at init time
