### ISSUE TITLE
login failures after upgrade to Smooch sdk 6

### ISSUE THREAD

**Issue by adbl** [smooch/smooch-ios#182]
We use Smooch iOS SDK (via https://github.com/smooch/react-native-smooch), and have just upgraded from Smooch 4.x to Smooch 6.x. 

Since our updated app became available in App Store a few days ago I have observed plenty of login calls failing like this:

```
      "message": "",
      "domain": "NSURLErrorDomain",
      "code": "",
      "userInfo": {
        "NSLocalizedDescription": "URL som inte stöds",  // (like "URL which is not supported", localized to swedish)
        "NSErrorFailingURLStringKey": "(null)/apps/<snip>/login", // snip is a hex-string
        "NSErrorFailingURLKey": {},
        "NSUnderlyingError": {
          "code": "-1002",
          "message": "underlying error",
          "domain": "kCFErrorDomainCFNetwork",
          "userInfo": {}
        }
      }
``` 

Something is `null` which isn't supposed to be. I'm sure it doesn't happen every time, could it be related to Smooch 4.x state? 
Or could this happen due to `[Smooch initWithSettings ...]` failing (we are not logging that currently), if so, what could cause it to fail?

**Comment by mspensieri** [comment]
It's hard to tell what the issue could be without sample code, but if the base URL is `(null)` as is shown in your error snippet (`"(null)/apps/<snip>/login"`), it probably means that the call to `init` failed or was not complete when login was called. Are you calling login after `initWithSettings` succeeds?

```objc
[Smooch initWithSettings:settings completionHandler:^(NSError * error, NSDictionary * userInfo) {
    if (!error) {
        [Smooch login:userId jwt:jwt completionHandler:nil];
    }
}];
```

**Comment by adbl** [comment]
@mspensiery We use the react native library. We call init from AppDelegate but are not logging it so not sure if it has succeeded. All our error handling is done on JS side...

We are basically doing the same thing as we did with Smooch v4: init smooch when app launches and call login early from js side once we have loaded user state. But there was no error reporting on js side from login before so maybe we had this problem already. Although all users who contact us via Smooch has been logged in.

I can add init support in your react bridge to enable error reporting, but also to retry init if it has failed. But I wonder if that could cause trouble for an initial push notification that may have been tapped? If this is not a good idea, is there some way to determine if Smooch has been initialized properly?

**Comment by mspensieri** [comment]
> I can add init support in your react bridge to enable error reporting

Sure, pull requests are always welcome

> but also to retry init if it has failed

Init will automatically retry itself a number of times if the failure was due to anything except invalid credentials, so you shouldn't need to retry it manually. The completion handler will only be called after all retries are exhausted.

> is there some way to determine if Smooch has been initialized properly?

Passing a callback block to `initWithSettings` is the way to know. You can also listen to `SKTInitializationDidCompleteNotification` and `SKTInitializationDidFailNotification` via `NSNotificationCenter`

**Comment by adbl** [comment]
Good to know! Can you comment on if this would cause any trouble in the Smooch push notification triggering app launch scenario, since init is called a bit later? (Thinking about Swizzling and iOS stuff which I know nothing about..)

**Comment by mspensieri** [comment]
Can you explain the scenario a bit more? When an app launches in response to a push notification tap, the `application:didFinishLaunchingWithOptions:` method is still called so if your `initWithSettings:` call is in there you should be fine. The user who was logged in on the previous app launch will still be logged in, there is no need to call the `login` API again.

**Comment by adbl** [comment]
So, if I implement “init” support in react-native-smooch (because I want to do error logging/handling in JS), it will not be called in `didFinishLaunching...` anymore, but shortly afterwards when the JS runtime is loading. This is why I’m concerned it might cause an issue in the push scenario.

**Comment by mspensieri** [comment]
If `initWithSettings:` is not called before `applicationDidBecomeActive:` then the conversation screen will not show in response to a push notif tapped, regardless if you are using `login` or not. The init does not need to complete, it just needs to be called before then.

If `initWithSettings:` is called after `applicationDidBecomeActive:`, then you'd need to figure out that the app was launched from push yourself, and call `[Smooch show]` manually

**Comment by adbl** [comment]
Ok, that should be possible. Thanks!
