### ISSUE TITLE
Typing Indicator showing 

### ISSUE THREAD

**Issue by dsrijan** [smooch/smooch-ios#183]
After Integrating with Smooch in our iOS App, Chatting works fine for first time but when we kill and run app again then message from iphone to server being sent but server to iOS app not showing and at the end there is always typing indicator showing in iOS App.

I had push notification enabled with my iOS app and background fetch for remote notification is also enabled. I am struck badly here since user is not able to chat.

Please let me know asap

**Comment by mspensieri** [comment]
Hi @dsrijan, I'm not sure I understand what's happening here. Can you provide a screenshot, short video, or sample project reproducing the issue please? Also, which version of the SDK are you using?

**Comment by dsrijan** [comment]
Hi @mspensieri , Issue is very simple. On first connection,means if i am contacting smooch server for the first time, it's working perfectly means I am able to send msg to smooch server and smooch server is able to revert the reply.
But, once i kill the app and start chat with smooch server, then my msg from iPhone to smooch server is going but smooch server msg is not coming at iOS. 

I had properly create push notification also for the same project.

If issue is not clear then kindly  share me an email id on which I share the video of this issue.

**Comment by dsrijan** [comment]
Since, we are making customers using Smooch chat so, it's going to be a big deal for future. I am Srijan from Ameyo Team.

**Comment by dsrijan** [comment]
Please check the video and lemme know
https://www.dropbox.com/s/hhjwszjrfvb2to4/VID_20171121_135454028.mp4?dl=0

**Comment by dsrijan** [comment]
@mspensieri getting this error in dashboard. Please lemme know whts the issue

Push notification transmission error. Apple returned <b>code 8</b>. See more info <a class='url page-reload' href='https://developer.apple.com/library/prerelease/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/BinaryProviderAPI.html'>here</a>.

**Comment by mspensieri** [comment]
Error code 8 means the provisioning profile used to sign your application does not match the certificate you've uploaded to send push notifications. The most common reason for this is using a production certificate to send push to a development application.

I believe you have an open thread with our customer success team regarding your original problem, so I'll close this issue. Please direct future questions through that other thread instead of GitHub, and we'll do our best to help!
