### ISSUE TITLE
Completion handler of Smooch.login

### ISSUE THREAD

**Issue by janweinkauff** [smooch/smooch-ios#184]
Does ```Smooch.login(userId:, jwt:, completionHandler:)``` call the completion block every time or are there exceptions?

If an user is logged in I see the following message in the console:
```<SMOOCH::WARNING> User XXX already logged in. Ignoring!```
and the completion block isn't called. 
I also tried to catch the notification `SKTLoginDidCompleteNotification`.

Is it possible to recognize if Smooch will not call the completion block?

**Comment by wmora** [comment]
The call to `login` is ignored when:

* Credentials are invalid (empty or nil userId/jwt)
* Smooch hasn't initialized yet
* `SKTConversationViewController` is currently displayed
* Credentials are the same as the ones used in the current session (the message you received)

The only way you can detect whether `login` will be ignored or not today is to add those checks in your code before calling the method.

**Comment by mspensieri** [comment]
FYI as of v6.6.1 the completion handler will be invoked with an error if the call was ignored
