### ISSUE TITLE
How are you differentiating two user using same appId

### ISSUE THREAD

**Issue by dsrijan** [smooch/smooch-ios#189]
Hello

I am using your latest iOS SDK. Can you please tell me how are you differentiating history of Smooch Chat. Since, If I am not providing any email id and first/last name then would the same chat history will be showing in every phone or you are differentiating using the UUID.

`       let   settings = SKTSettings(appId: withAppId)
        Smooch.initWith(settings, completionHandler: nil)
        Smooch.show()`

Would every phone showing the same history in this case ?

A quick response needed.

**Comment by mspensieri** [comment]
When Smooch is launched for the first time on a new device (or simulator), it generates a random identifier for that device and persists it. That identifier then uniquely identifies your app installation, and is used to distinguish different users. So no, the same chat will not appear on every device.

Not also that email address, first name and last name are not identifying factors for a user. Multiple users can share the same email or name and not have the same conversation history. If you would like to allow a user to access their history across multiple devices, you need to use the `login` API to assign them a `userId`.

See [introduction to users](https://docs.smooch.io/guide/intro-to-users/), [managing user information](https://docs.smooch.io/guide/managing-user-information/), and [authenticating users](https://docs.smooch.io/guide/authenticating-users/) for more information.

**Comment by dsrijan** [comment]
Is there any possibility to clear history from iOS Chat ?

**Comment by mspensieri** [comment]
To clear the history for a given user, you can use the [Delete Messages API](https://docs.smooch.io/rest/#delete-messages) from your backend. There is no way to call this API from iOS at the moment.

Otherwise, if you switch users by using [`+login:jwt:completionHandler:`](https://docs.smooch.io/api/ios/Classes/Smooch.html#//api/name/login:jwt:completionHandler:), or [`+logoutWithCompletionHandler:`](https://docs.smooch.io/api/ios/Classes/Smooch.html#//api/name/logoutWithCompletionHandler:) (if the user is logged in), then the history for the new user will be displayed

**Comment by dsrijan** [comment]
You guyz recently come with Custom UI for iOS and Android. Still there is no API for Delete history in Custom UI also ?

**Comment by mspensieri** [comment]
> You guyz recently come with Custom UI for iOS and Android.

We recently published a _guide_ on how to write your own custom UI, but using your own UI has been supported for years now.

> Still there is no API for Delete history in Custom UI also ?

That's right, we only support clearing the history from the backend at the moment. I'll bring your request to the team for discussion, can you describe the use case?

**Comment by dsrijan** [comment]
Actually we earlier started implementing ur own UI but there were a lot lags so we now decided with Custom UI which u guyz already provided.
Our use case is that we are providing our customer to clear the history if they want.. If you guyz will suggest me is there any way to share messages over email, would it be also possible ?

**Comment by mspensieri** [comment]
You can use the [link user to channel](https://docs.smooch.io/rest/#link-app-user-to-channel) API to subscribe a user to receive email messages using your [mailgun integration](https://app.smooch.io/integrations/mailgun)

**Comment by dsrijan** [comment]
![imgttt](https://user-images.githubusercontent.com/8248956/37021471-b18d7e24-2145-11e8-8d5d-2fa782728211.jpeg)
Hi, quick question, on iOS ten when we push chat, there is a Done button, can we hide it somehow? (Ignore the fact that title is not centerd)

**Comment by mspensieri** [comment]
There is currently no API to hide that button, it displays only in the case where the conversation view controller is contained in a `UITabBarController` and the keyboard is shown. It was added in response to https://github.com/smooch/smooch-ios/issues/130 and is used to allow the user to dismiss the keyboard easily

**Comment by dsrijan** [comment]
But on UX Point of view, it's looking not cool. This issue is coming only in iOS 10. In iOS 11, it's working fine and there is no Done Button coming there.
And yest we are using over Tabbarcontroller. Please provide us better alternative cz our team won't be able to release our Chat Application with this UX since many customers might be yet using iOS 10.
