### ISSUE TITLE
How to delete chat history from iOS SDK on logout from parent application

### ISSUE THREAD

**Issue by dsrijan** [smooch/smooch-ios#190]
How to delete the history in Smooch iOS SDK

I am using Smooch in built UI and opening Smooch View by simply provided code
` Smooch.show()`

Now, my use case is deleting the history when I logout from my parent mobile application

i.e., I switch account from A to B but I still see chat history of account A

Please provide the solution on urgent basis.

**Comment by mspensieri** [comment]
You can see the result of the logout call by passing a `completionHandler` and inspecting the response.

```objectivec
[Smooch logoutWithCompletionHandler:^(NSError * _Nullable error, NSDictionary * _Nullable userInfo) {
    NSLog(@"Logout complete: %@ %@", error, userInfo);
}];
```

I suspect you're calling `logout` when there is no user currently logged in, resulting in a no-op.

On a separate note, please keep in mind the GitHub issue template is there for a reason, and this repository should only be used for bug reports, not for feature requests or general support questions such as this one. As I understand it, you've also sent an email to our support team with this information, I'll let them debug this problem with you further.
