### ISSUE TITLE
iOS SDK, prevent notification banners in active app 

### ISSUE THREAD

**Issue by drct** [smooch/smooch-ios#196]
Since I cannot find anything in your documentation I'll try here (btw, your docs on the native iOS SDK still refer to iOS 10): When I start the app (iOS, native SDK, custom conversation view) the user is logged in to Smooch and then a notification banner is shown with the latest message. I have managed to disable the Smooch conversation view that appears when the user taps on that banner but is there any chance to completely disable such notification banners when the app is active? Thanks

 **Please tell us about your environment:**
- SDK version: 6.10.0
- OS version: iOS 11.4

**Comment by mspensieri** [comment]
If you return `false` in [`conversation:shouldShowInAppNotificationForMessage:`](https://docs.smooch.io/api/ios/Protocols/SKTConversationDelegate.html#//api/name/conversation:shouldShowInAppNotificationForMessage:) it will prevent Smooch from showing any kind of banner while the app is in the foreground

**Comment by drct** [comment]
No, I have implemented this method and still a banner is shown.

**Comment by drct** [comment]
We are using our own chat implementation, because we need to display other messages beside the built-in ones. In "didFinishLaunchingWithOptions" we set the UNUserNotificationCenter delegate, the we initialise Smooch with settings but the chat, which is also the delegate, is not available at that time. We set the Smooch conversation delegate later.

BTW: It would be nice to be able to check whether a user is logged in or not. As far as I know there is currently now way to check the user's login status.

**Comment by mspensieri** [comment]
> We set the Smooch conversation delegate later.

The delegate must be set at the time the notification is about to be shown, so if you want to hide notifications on app launch, then the delegate needs to be set in `didFinishLaunchingWithOptions`.

**Comment by drct** [comment]
I changed the responsibilities of some of my objects and now it seems to work. Thanks a lot.

What unfortunately does not work is this:
- App is in background (Smooch was initialised and a Smooch user was logged in before going to the background)
- User taps on a notification (banner)
- App opens and the conversation is reloaded and shown
=> The message belonging to the notification the user tapped on is not in the array I get from the conversation object.
=> If the user logs out and back in again the previously missing message is shown.
Any ideas why this might be? Thanks

**Comment by drct** [comment]
`–conversation:didReceiveMessages:` unfortunately is never called. When I reload the conversation's messages for a second time the missing message is there. But `–conversation:didReceiveMessages:` was never called after tapping on the notification banner.

**Comment by mspensieri** [comment]
Can you share a sample project reproducing the issue?

With the following code:

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    /* ... */
    
    SKTSettings* settings = [SKTSettings settingsWithAppId:APP_ID];
    [Smooch initWithSettings:settings completionHandler:^(NSError * error, NSDictionary * userInfo) {
        NSLog(@"Init complete: %@ %@", error, userInfo);
    }];
    [Smooch conversation].delegate = self;
    
    return YES;
}

-(BOOL)conversation:(SKTConversation *)conversation shouldShowForAction:(SKTAction)action withInfo:(nullable NSDictionary *)info
{
    NSLog(@"Push notification tapped");
    return YES;
}

-(void)conversation:(SKTConversation *)conversation didReceiveMessages:(NSArray *)messages
{
    NSLog(@"Messages received! %@", messages);
}

- (void)applicationDidEnterBackground:(UIApplication *)application
{
    NSLog(@"App went to background");
}

- (void)applicationDidBecomeActive:(UIApplication *)application
{
    NSLog(@"App became active");
}
```

I get this as log output:

```
2018-07-06 08:02:36.828491-0400 ShellApp[19618:11012255] App went to background
2018-07-06 08:02:47.051729-0400 ShellApp[19618:11012255] Push notification tapped
2018-07-06 08:02:47.391077-0400 ShellApp[19618:11012255] App became active
2018-07-06 08:02:48.073524-0400 ShellApp[19618:11012255] Messages received! (
    "<SKTMessage: 0x1c4129b00>"
)
```
