### ISSUE TITLE
iOS 13 issues (Dark mode and attachments)

### ISSUE THREAD

**Issue by ph1lb4** [smooch/smooch-ios#202]
**What is the current behavior?**
Dark mode on iOS 13 is not properly supported. The background of the chat is white. Also it is not possible to click on the + and add an attachement.

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem**. Ideally a sample project

Try out Smooch on iOS 13 with dark mode.

 **What is the expected behavior?**
Dark mode is supported and attachments can be added.

 **Please tell us about your environment:**
- SDK version: Latest
- OS version: 13.0 beta 8

**Comment by wmora** [comment]
Thanks for reporting, we're working on iOS 13 support and will release the new version as soon as XCode 11 GM is out. I'll update this issue when done

**Comment by wmora** [comment]
Fixed in version 7.0.1. Let me know if you run into any other issues. Thanks for reporting!
