### ISSUE TITLE
Keyboard hiding textfield

### ISSUE THREAD

**Issue by mansoorshahsaid** [smooch/smooch-ios#205]
**I'm submitting a ...**
  - bug report

 **What is the current behavior?**
When presenting smooch by doing [Smooch show]; the keyboard is on top of the input textfield and hides the user from seeing what he's typing.

![Simulator Screen Shot - iPhone 8 - 2019-11-26 at 11 28 43](https://user-images.githubusercontent.com/22176322/69652601-ed649f00-103f-11ea-922c-c28c42038e87.png)

 **Please tell us about your environment:**
- SDK version -- 6.16.0
- OS version -- 13.2

**Comment by btgaston** [comment]
im experiencing the same issue.

**Comment by mansoorshahsaid** [comment]
@btgaston that fixed the issue, thanks!
