### ISSUE TITLE
Pod broken

### ISSUE THREAD

**Issue by Dids** [smooch/smooch-ios#57]
For some reason the Pod broken for me entirely, with Xcode not being able to find SupportKit.h.
This ended up being a directory issue, as Cocoapods was trying to look for the headers in "${PODS_ROOT}/Headers/Public/SupportKit" but couldn't find them.

Thing is, for some reason SupportKit is placing the headers in a subfolder called SupportKit, meaning the path becomes "${PODS_ROOT}/Headers/Public/SupportKit/SupportKit" instead, which breaks automatic pod install/update.

**Comment by mspensieri** [comment]
Possibly related to https://github.com/CocoaPods/CocoaPods/issues/3499

**Comment by mspensieri** [comment]
@Dids do you still have this issue with the Smooch pod?
