### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ekurutepe** [smooch/smooch-ios#59]
Are there any plans to support Carthage?

**Comment by chbeer** [comment]
+1 for Carthage support

**Comment by mspensieri** [comment]
Sorry for delayed response on this one. Carthage support is blocked by the fact that Smooch is bundled as a static framework, rather than an iOS dynamic framework.

> Note that Carthage only supports dynamic frameworks, which are only available on iOS 8 or later (or any version of OS X).

https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

We still would like to maintain support for iOS 7, so upgrading to dynamic frameworks is not really an option at this point. Unless you guys know of a workaround?

**Comment by chbeer** [comment]
You can set the deployment target and base sdk per target. It seems you don't even have a framework target, yet. So just add it with deployment target 8.0 and share the framework so that it's available for Carthage

**Comment by gemmakbarlow** [comment]
@mspensieri One side effect of this static framework inclusion for CocoaPods users; they (as I've just discovered) can't use pods written solely in swift if SupportKit is also in their Podfile. 

Adding the `use_frameworks!` directive in my pod file results in the following:

```
CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Smooch (3.5.1)
Installing SmoochHelpKit (1.0.2)
cd [!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/gemmakbarlow/Development/about-me/Gemma Barlow/Gemma Barlow/Pods/Smooch/Smooch.framework)

```

Just wanted to check that you were aware of this in considering whether to continue iOS 7 support.

**Comment by mspensieri** [comment]
@gemmakbarlow This issue should only affect users of `SmoochHelpKit`, see https://github.com/smooch/smooch-helpkit-ios/issues/4

**Comment by gemmakbarlow** [comment]
@mspensieri Got it, thanks.

**Comment by mspensieri** [comment]
Carthage is now supported on the 4.x series of releases
