### ISSUE TITLE
Console message for new version but have the latest version

### ISSUE THREAD

**Issue by nbwar** [smooch/smooch-ios#60]
I'm getting a console message to update Smooch `There is a new Smooch version available. You have 3.0.0, version  is available. Visit https://github.com/smooch/smooch-ios to download it or do a 'pod update'` But 3.0.0 is the latest version.

**Comment by mspensieri** [comment]
Should be fixed now, I forgot to name the v3.0.0 release :) Can you test again?

**Comment by nbwar** [comment]
Yup its all fixed!
