### ISSUE TITLE
Smooch 3.0.0 causes mysterious crash

### ISSUE THREAD

**Issue by fatuhoku** [smooch/smooch-ios#61]
I did a write up of this over at http://stackoverflow.com/questions/33615863/mysterious-crash-in-ios-9-sktappdelegate-applicationdidreceivelocalnotificat. Please refer to that.

I tried 3.0.1, and can verify that this version has fixed this crash.

Noting this here for posterity.

**Comment by mspensieri** [comment]
Thanks for the report. Closing this issue since the crash is fixed
