### ISSUE TITLE
For cordova no known method for selector 'showConversation'

### ISSUE THREAD

**Issue by okpatil4u** [smooch/smooch-ios#65]
I am following http://docs.smooch.io/ios/#manual-method manual for installing smooch for cordova, I am having above error while building.

**Comment by edchan77** [comment]
It was fixed in this commit:https://github.com/smooch/smooch-cordova/commit/2ba67db9962d50d571b21fa405371f5b72b6cd0a

How did you pull the cordova plugin btw? plugman?

**Comment by edchan77** [comment]
Fixed. Use show() instead!
