### ISSUE TITLE
Be able to verify if a notification is from Smooch or not

### ISSUE THREAD

**Issue by natanrolnik** [smooch/smooch-ios#68]
Hi! 

In my app, when I receive a notification, the default behaviour is to show an `UIAlertController` with the alert text. However, if the notification comes from Smooch, I want to show the beautiful UI via `handleNotification:`.

Currently, the only way I could do this was checking for the word "smooch" in the dictionary keys. Of course, this is far from ideal, because in the future if you decide to change the keys, this could break. 

This is what I did temporarily:

```obj-c
BOOL containsSmooch = NO;
    
    for (NSString *key in [userInfo allKeys]) {
        if ([[key lowercaseString] rangeOfString:@"smooch"].location != NSNotFound) {
            containsSmooch = YES;
            break;
        }
    }
    
    if (containsSmooch) {
        [Smooch handlePushNotification:userInfo];
        
        return;
    }

    //show the standard alert controller
```

Do we have any other way to check if a notification comes from Smooch? Do we have any constants for the used keys in the dictionary?

Thanks

**Comment by mspensieri** [comment]
You can verify the origin by doing the following:

```objc
if(userInfo[@"SmoochNotification"]){
}
```

We'll make sure to expose this as a constant in a future release!

**Comment by natanrolnik** [comment]
Yes, I checked the `userInfo` dictionary and noticed this key. I'm just afraid that this may change in the future, so that's why I preferred to do the search for "smooch" in the keys... But the fact of being a constant is already an improvement. Waiting for it :smile: !

**Comment by mspensieri** [comment]
v3.3.0 now exposes the constant `SKTPushNotificationIdentifier` for this purpose
