### ISSUE TITLE
Conversation unread count returns 0

### ISSUE THREAD

**Issue by modastic** [smooch/smooch-ios#70]
When a push notification is received, checking the value [Smooch conversation].unreadCount gives 0 while the app is running in the background.

This also happens with the unreadCountDidChange callback while app is running in the background

**Comment by mspensieri** [comment]
Thanks @modastic. This is a known issue and is related to the fact that we store unread count on the device side and not the server side. We have plans to fix this, will keep this issue open until that happens.

**Comment by fatuhoku** [comment]
+1 very very much needed. Currently users have no idea, other than from remote notifications, that we have messaged them at all.

**Comment by mspensieri** [comment]
Starting with v4.0.0, you can now have Smooch manage the badge for you automatically, check out the new checkbox in the push settings UI

<img width="663" alt="screen shot 2016-03-03 at 11 14 56 am" src="https://cloud.githubusercontent.com/assets/2286852/13500630/5e7557b2-e131-11e5-9135-b38d4cc7a0ae.png">

**Comment by fatuhoku** [comment]
Great implementation!

**Comment by kurse** [comment]
Hi! I am having the same issue on Android, when I call the Smooch.init() function I receive the in-app notification on the unread message, which makes the unreadCount always return a 0 because seeing how it's implemented you seem to take into account if the notification was shown. This makes it so we can never get a proper unreadCount as it'll always show 0, making it impossible for us to show the user the number of unread messages, and not even if he has unread messages or not. I hope you have a suggestion for us to get around it or hopefully have a fix in the way. Thank you.

**Comment by mspensieri** [comment]
> because seeing how it's implemented you seem to take into account if the notification was shown

The unread count should not be reset when the notification is shown. Unread count is reset when:

1. The conversation screen is opened
2. The developer calls [`markAllAsRead`](https://docs.smooch.io/api/ios/Classes/SKTConversation.html#//api/name/markAllAsRead) on `SKTConversation`
3. A new message arrives when the conversation screen is displayed

@kurse Are you calling `[Smooch show]` during your application startup logic?

**Comment by kurse** [comment]
@mspensieri I don't call a smooch show, the only thing the app does is to initialise everything: 
`      Settings settings = new Settings(getString(R.string.smooch_token));
        settings.setUserId(id);
        Smooch.init(this, settings);`
When I do that, If the user happens to have an unread message it shows as a notification, but the unread count return 0. The reason I said that you seem to take into account if the notification was shown is when inspecting your implementation of isRead: 
`public boolean isRead() {
        a var1 = this.c.k();
        return var1 != a.StatusUnread && **var1 != a.StatusNotificationShown;**
    }`
There is also a similar logic in the getUnreadCount function.

**Comment by mspensieri** [comment]
Oh I missed the fact that you were using Android. I would suggest to open an issue on the [smooch-android](https://github.com/smooch/smooch-android) repo instead, and one of our Android developers can help you there

**Comment by kurse** [comment]
I will, thank you @mspensieri !
