### ISSUE TITLE
Two finger swipe down to open

### ISSUE THREAD

**Issue by ajinkyashelar** [smooch/smooch-ios#71]
Hi,

I had implemented the SupportKit in one of my iOS app to chat with the users. It had the cool feature of two finger swipe down to open the chat from any where in the app. I find it missing in the Smooch SDK. 

Please let me know if it has been discontinued or I am missing something.

**Comment by mspensieri** [comment]
@ajinkyashelar The two finger swipe gesture, along with some other features like recommendations and zendesk search, have been split into a separate open-source repo called [smooch-helpkit](https://github.com/smooch/smooch-helpkit-ios). Follow the instructions in the readme to set it up!
