### ISSUE TITLE
Smooch 3.3.1: `UITextField` on conversation view no longer calls `resignFirstResponder` if view isn't active

### ISSUE THREAD

**Issue by beaker-sbo** [smooch/smooch-ios#72]
Using SWRevealViewController, and instantiating a new conversation view with `newConversationViewController` for tapping on a Feedback menu item in our `rearViewController` (the app "drawer" menu controller), correctly instantiates a new conversation view controller, and sets up the `UITextField` as the first responder.

However, if the app's side "drawer" menu is opened, making the view no longer the active view, `resignFirstResponder` is no longer called on the `UITextField` (I confirmed this by setting a symbolic breakpoint and testing whether or not it was called during the menu opening action). This used to be called on the same `UITextField` in SupportKit 2.11.1, so I'm not sure what changed.

Is this new behavior that must be set with SmoochHelpKit? If so, how might I go about this?

**Comment by mspensieri** [comment]
With v3.5.3 you can now user `[viewController resignFirstResponder]` on the conversation view controller, or call `[viewController.view endEditing:YES]`
