### ISSUE TITLE
Unread count being reset when app restores state

### ISSUE THREAD

**Issue by ivanbruel** [smooch/smooch-ios#73]
Calling `Smooch.show()` and even `Smooch.conversation().markAllAsRead()` clears the unread count but when the app is resumed or re-opened it shows the `unreadCount` as `1`.

This only happens when the user is not the last one to write in chat window.

Any function I should call to actually save the state?

**Comment by mspensieri** [comment]
Hmm nope, looks like a bug on our side. Will investigate, thanks

**Comment by mspensieri** [comment]
Should be fixed by v3.5.2, just released
