### ISSUE TITLE
Images are not being uploaded

### ISSUE THREAD

**Issue by bartoszhernas** [smooch/smooch-ios#74]
Hey, whenever I try to send an image from chat from inside my app, the image shows on the screen and there is label `sending` all the time.

I have waited few minutes but nothing happened.
Any ideas?

**Comment by mspensieri** [comment]
@bartoszhernas Which sdk version are you on? I just tried the latest 3.5.2 and it seems to be working

![img_upload](https://cloud.githubusercontent.com/assets/2286852/13178424/e08832a0-d6ec-11e5-8a2e-ed30d9c80ad7.gif)

**Comment by bartoszhernas** [comment]
I am on `  - Smooch (3.5.1)`. Will try to update then :)

**Comment by mspensieri** [comment]
Closing this since I can't repro on latest version, please reopen if it shows up again

**Comment by bartoszhernas** [comment]
I have 3.5.2 now and it doesn't upload. Can it be the issue with picture size? 
I am testing it on iPhone 6Plus.

On Simulator it uploads successfully. Can I somehow provide you with some logs?
I am testing using Smooch account "b@hern.as" using team "WhatsAhoyStaging"

**Comment by bartoszhernas** [comment]
Screenshot from iPhone: https://www.dropbox.com/s/quz1kokwt04gjj5/2016-02-24%2019.08.02.png?dl=0

**Comment by mspensieri** [comment]
Should not be an issue with image size since we rescale the image before uploading. Would be great if you could provide me a userId and timestamp of this failing and I can check our logs

**Comment by bartoszhernas** [comment]
@mspensieri I think it was some network problems because now everything works fine. Thanks for help!
