### ISSUE TITLE
Two conversations, same user

### ISSUE THREAD

**Issue by jamesallison** [smooch/smooch-ios#76]
I log in the user with two different methods:

```
// user is already logged in to my app, so init Smooch with the user logged in
let settings = SKTSettings(appToken: "apptoken")
settings.userId = username
Smooch.initWithSettings(settings)
SKTUser.currentUser().firstName = username
SKTUser.currentUser().email = username! + "@domain.com"
```

```
// when the user logs in to my app during it running; so the app has started with on user logged in or a new one has logged in:
Smooch.login(username, jwt:nil)
SKTUser.currentUser().firstName = username
SKTUser.currentUser().email = username + "@domain.com"
```

I then in slack see two different channels randomly, but from this same user:
`#asampleusername` and `#asampleusername-8584`

Not just slack, the chat history in the iOS-end also alternates between these two. What's going on here?

**Comment by jamesallison** [comment]
This wasn't observed before, Smooch team looking into it soon.

**Comment by qadirsuh** [comment]
any update regarding this. I am facing it too. 
here is my log
2017-10-10 12:56:09.943411+0500 jamesAppV2[295:33338] <SMOOCH::INFO> Logout called, but no user was logged in. Ignoring!
2017-10-10 12:56:09.943625+0500 jamesAppV2[295:33338] <SMOOCH::WARNING> Login called with nil or empty jwt. Ignoring!
2017-10-10 12:56:09.943984+0500 jamesAppV2[295:33338] <SMOOCH::INFO> Logout called, but no user was logged in. Ignoring!
2017-10-10 12:56:09.944068+0500 jamesAppV2[295:33338] <SMOOCH::WARNING> Login called with nil or empty jwt.

**Comment by wmora** [comment]
@qadirsuh I think you are talking about a different issue. Note that if you are using version 6.x of the SDK you cannot log in without a jwt. See the [release notes](https://github.com/smooch/smooch-ios/releases/tag/6.0.0) for more detail.

If you're still facing an issue, please report in a separate GH issue. Thanks!

**Comment by qadirsuh** [comment]
@wmora thanks for this, this looks like smooch upgrade issue, 
I have posted a new question.
https://github.com/smooch/smooch-ios/issues/172
