### ISSUE TITLE
Clear documentation + code snippets showing how to display Smooch unread message count as app notification badge

### ISSUE THREAD

**Issue by fatuhoku** [smooch/smooch-ios#77]
Y'know, something like this:

![screen shot 2016-02-24 at 14 22 02](https://cloud.githubusercontent.com/assets/430233/13288039/01d1b5b2-db02-11e5-8230-7c1f71c63633.png)

Otherwise our users have no idea we've messaged them at all!

**Comment by fatuhoku** [comment]
Related to #39 and #70

**Comment by mspensieri** [comment]
See https://github.com/smooch/smooch-ios/issues/70#issuecomment-191833000
