### ISSUE TITLE
Everytime i start my app , i get too old messages as push notifications.

### ISSUE THREAD

**Issue by NEITISH** [smooch/smooch-ios#78]
i have oberved that , as soon as my smooch code is initialised , i get notification of first messages received on my slack, coz i have connected smooch with slack.
and everytime i open app i get same no. of unread count message , why ,don't know. though i have read all the messages on smooch chat ui but still i always get some unread message count.

Your help is needed.

**Comment by mspensieri** [comment]
@NEITISH What sdk version are you on? This was supposed to have been fixed in [v3.5.2](https://github.com/smooch/smooch-ios/releases/tag/3.5.2)

**Comment by mspensieri** [comment]
Closing as this has been fixed, please reopen if it re-appears on the latest version
