### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ctews** [smooch/smooch-ios#80]
Hey guys,

as soon as I run the unit tests for every Swift class that implements Smooch methods I get the following error. Do you ship Smooch with x86_64 symbols? Would be really good to get those, because having Smooch and not be able to run unit tests without any modifications would be really bad :(

```Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Smooch", referenced from:```

Thanks in advance!

Cheers

**Comment by mspensieri** [comment]
We do indeed ship with `x86_64` symbols:

```
smooch-ios (master) $ lipo -info Smooch.framework/Smooch 
Architectures in the fat file: Smooch.framework/Smooch are: armv7 armv7s i386 x86_64 arm64 
```

Maybe the framework is not linked to your test target? Or perhaps the `Framework Search Paths` or `Header Search Paths` are misconfigured for that target?

**Comment by ctews** [comment]
Thanks for the hint @mspensieri! I guess my brain was out of order ;) Haven't linked the Smooch pod against the test target! :)
