### ISSUE TITLE
too much gap between smooch chat uitextfield and keyboard when i focus on uitext field

### ISSUE THREAD

**Issue by NEITISH** [smooch/smooch-ios#81]
![screen shot 2016-02-29 at 1 51 44 am](https://cloud.githubusercontent.com/assets/16499873/13387683/260c3794-de87-11e5-881d-26f9a382f208.png)
Hi,

i am using smooch slack integration. i am facing issue in ui part. there is uitextfield to write message and click send. as soon as i focus inside uitextfield to write something , keyboard comes up but there is much gap between the message uitextfield and the keyboard. see my attachement.

![screen shot 2016-02-29 at 1 45 42 am](https://cloud.githubusercontent.com/assets/16499873/13387628/b9cc1a2c-de86-11e5-8265-d8efd1bcbe9c.png)

**Comment by mspensieri** [comment]
Hm that's not good... Can you tell me a little bit about your setup? Is the Smooch conversation in a `UITabBarController`? Or did you simply present it using `[Smooch show]`

**Comment by NEITISH** [comment]
It is just a `[Smooch show]`

**Comment by mspensieri** [comment]
Where does that `Done` bar come from in your screenshot? I am able to reproduce this issue, but only when Smooch is in a `UITabBarController` with `translucency: false` on the tab bar

**Comment by NEITISH** [comment]
we have not this UI.. this is automatically created with smooch sdk and we have not used `UITabBarController` anywhere in our app , we have just made `UINavigationController` hidden everywhere.

**Comment by mspensieri** [comment]
Do you think you could put together a sample project that reproduces the issue? I can't figure out how to reproduce this otherwise

**Comment by beingshashi** [comment]
Hi, i have created sample project and also added some things required for my project , which might be creating the issue.
[SmoochTest](https://www.wetransfer.com/downloads/f653424ecf99baad1f3cffe489e7b99820160302103844/0f5e5fa63e7b5cd807215b0dbc18add420160302103844/e43773)

**Comment by mspensieri** [comment]
I was able to work around this issue using the following code: (requires v4.1.0 or greater)

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

/* .... */

    [Smooch initWithSettings:smoochSettings];
    
    [Smooch conversation].delegate = self;

/* .... */
    
    return YES;
}

-(void)conversation:(SKTConversation *)conversation willShowViewController:(UIViewController *)viewController
{
    [IQKeyboardManager sharedManager].enable = NO;
}

-(void)conversation:(SKTConversation *)conversation didDismissViewController:(UIViewController *)viewController
{
    [IQKeyboardManager sharedManager].enable = YES;
}
```

**Comment by PvUtrix** [comment]
We're having a similar issue when using the web version in a hybrid mobile app.

**Comment by mspensieri** [comment]
@PvUtrix does your app also integrate `IQKeyboardManager`, or is it a different library that is conflicting?

**Comment by PvUtrix** [comment]
@mspensieri yep and yep

**Comment by mspensieri** [comment]
@PvUtrix in that case, those are two completely separate codebases. I suggest you open an issue there with more information :)
