### ISSUE TITLE
Getting push notifications twice from slack

### ISSUE THREAD

**Issue by NEITISH** [smooch/smooch-ios#82]
Hi,
i am using smooch ios library integrated with slack. i have allowed push notifications. but whenver i reply from slack to my app , i get 2 notifications with same message text.

Any help.

**Comment by mspensieri** [comment]
This can sometimes happen when you are assigning a `userId` and the user uninstalls and re-installs your app on the same device - Smooch can treats that as two different devices, even though it's really just one. Do you know the `userId` of the user that is receiving more than one push?

**Comment by NEITISH** [comment]
we are getting `userId` from API response , and we are using that user ids , as smooch userid .. may be you can use '87120928` , if you need i can share my api key also.
Thanks

**Comment by mspensieri** [comment]
> if you need i can share my api key also
Yes please that would be helpful. Not sure if you want to post it publicly like this or not though, you can send it by email help@smooch.io

**Comment by mspensieri** [comment]
Replied by email, this use was in a inconsistent state. The user in question has been fixed, but it's filed as a bug on our side and we'll investigate the root cause
