### ISSUE TITLE
Building against Smooch 4.0.1 error: "Info.plist includes support for iOS Simulator"

### ISSUE THREAD

**Issue by wpearse** [smooch/smooch-ios#84]
**Steps to reproduce**

- Install Smooch 4.0.1 (latest) using cocoapods
- Archive your iOS app
- Export your iOS app, choose to rebuild from bit code
- Get error: ```Info.plist of “xyz.app/Frameworks/Smooch.framework” specifies a simulator platform for the CFBundleSupportedPlatforms key```

**Regression**

No problems when using Smooch 3.5.3. You can prove this by using:

```pod 'Smooch', '3.5.3'```

in your podfile.

**Comment by mspensieri** [comment]
Whoops, can you try 4.0.2?

**Comment by wpearse** [comment]
I opened my pod file, changed `pod 'Smooch', '3.5.3'` to  `pod 'Smooch'`. I then ran `pod update` and verified that Smooch 4.0.2 was now installed.

I cleaned the project, archived my app, exported the app, rebuilt from bit code.

No problems at all. Works great.

Thanks for the prompt fix!
