### ISSUE TITLE
start communication from slack to smooch app

### ISSUE THREAD

**Issue by beingshashi** [smooch/smooch-ios#85]
Hi,

i have been using smooch for our clients to reach to us. but what we want is that , start communication from slack to smooch chat of the user who has installed the app.
basically we want to understand , when user send message from smooch app to slack , the channel created automatically , with name similar like " sk-james-bond".
so is this possible or not? if yes what is the approach that we should take?

Thanks.

**Comment by mspensieri** [comment]
I don't think the use case you're describing is currently supported by the Smooch platform:

1. Smooch will only create a Slack channel when the user sends their first message - there's currently no way to link an existing Slack channel to a Smooch user, and start sending them messages.
2. The Smooch REST API unfortunately does not expose the channel id of a given Smooch user, so even if the user has started a conversation, and the Slack channel exists, there's no way to discover this through the API.

For 1) you could instead use a [Whisper](http://docs.smooch.io/ios/#whispers) or the [REST API](http://docs.smooch.io/rest/) to start a conversation with the user, but it won't show up in Slack until the user replies.

Support for 2) has been asked for before, and is in our backlog, so we may eventually support this.
