### ISSUE TITLE
Fatal Exception: UIApplicationInvalidInterfaceOrientation Supported orientations has no common orientation with the application, and [PUUIAlbumListViewController shouldAutorotate] is returning YES

### ISSUE THREAD

**Issue by fatuhoku** [smooch/smooch-ios#86]
Reproduction:

1. Create an application that's confined to the landscape orientation only
2. Activate the conversations window
3. Touch the camera icon
4. Select `Choose from Library`
5. Observe crash.

Tested on iPad Air.

**Comment by mspensieri** [comment]
Not sure what we can do about this issue, the crash isn't linked to Smooch - the standard iOS image picker controller is the one crashing. I've attached a sample project demonstrating the same issue (no Smooch framework added).

The main view controller has a `UITapGestureRecognizer` that invokes the following code on tap

```
UIImagePickerController* imagePicker = [[UIImagePickerController alloc] init];
imagePicker.sourceType = UIImagePickerControllerSourceTypePhotoLibrary;
[self presentViewController:imagePicker animated:YES completion:nil];
```

[ImagePickerTest.zip](https://github.com/smooch/smooch-ios/files/165909/ImagePickerTest.zip)

**Comment by fatuhoku** [comment]
@mspensieri Thanks for investigating. That's pretty terrible... I found this answer which uses categories hacks to get around the problem but it's not something I want to be rolling into my app.
