### ISSUE TITLE
Carthage download is faulty

### ISSUE THREAD

**Issue by pietbrauer** [smooch/smooch-ios#88]
When trying to download the framework using Carthage I noticed that it is not a real dynamic framework nor is it properly archived.

In order to provide a framework carthage notices you have to run `carthage build --no-skip-current` this will build all shared *framework* targets. Once you are done run `carthage archive Smooch` and it produces `Smooch.framework.zip`. It looks to me as if the `.zip` was done manually. Please also note that a frameworks automatically produces a module, which the current binary does not.

Any resources have to be provided in an extra `.bundle` file, not sure how to do that.

**Comment by mspensieri** [comment]
Thanks for the details @pietbrauer. Can you explain the impact of these issues? I have no warnings or errors running `carthage update`, linking the Smooch framework, running the app, invoking Smooch methods, or having Smooch resources loaded.

**Comment by pietbrauer** [comment]
I did not forget about this, I have better internet this week and will try again. When I run `Carthage update` it takes about 20 minutes to proceed and fails eventually. I will debug with better internet.

**Comment by pietbrauer** [comment]
Works :+1:
