### ISSUE TITLE
SmoochLocalization files lost after pod update to 4.0.2

### ISSUE THREAD

**Issue by MolevD** [smooch/smooch-ios#91]
Hi!

I updated pod file today from v 3.5.2. to 4.0.2. Now I don’t see _SmoochLocalizable.strings_ files in Xcode project. Could you please advise where to find them. 

Also, one interesting thing happens with localization. When I install my app to my iPhone directly with Xcode (development mode), I can see my custom text in Smooch window. But when I open my app via TestFlight (production mode), I see default Smooch texts in Smooch window.

**Comment by mspensieri** [comment]
@MolevD the string files can now be found in `Smooch.framework/*.lproj`, but I'm curious - are you modifying these files directly? If you add your own file to your app named `SmoochLocalizable.strings`, the Smooch SDK should prioritize that one over the one included with the framework, and allows you to override strings in that way

**Comment by MolevD** [comment]
Thanks for quick reply. Yes, I edited these files and updated text each time new Smooch version appear cause my custom text was overwritten by default Smooch text. Here is the screenshot of Smooch.framework. But I do not see strings... Or I just do not understand something 
![2016-03-17 17 21 06](https://cloud.githubusercontent.com/assets/17902236/13848995/a8aedd02-ec6d-11e5-9b97-aaa4c790b746.png)

**Comment by MolevD** [comment]
@mspensieri Mike, could you please reply to my additional comment?

**Comment by mspensieri** [comment]
It doesn't appear in XCode, but if you right click `Smooch.framework` and select "Show in Finder" you will find the files there. Like I said though, you shouldn't be modifying these files directly - you should instead create a new `SmoochLocalizable.strings` file and [put your strings in there](http://docs.smooch.io/ios/#strings-customization). `File -> New -> File -> iOS -> Resources -> Strings File`

<img width="1280" alt="screen shot 2016-03-17 at 2 06 38 pm" src="https://cloud.githubusercontent.com/assets/2286852/13856013/8ccf359c-ec49-11e5-9d94-20c612d7ba1f.png">

**Comment by MolevD** [comment]
@mspensieri Oh, now I see. I will prepare my own strings (it is even written in your docs, I was not careful when I read it.) But. To be able to provide my custom values I need original keys. I opened framework in a Finder like you tell me.

**Comment by MolevD** [comment]
@mspensieri Oh, now I see. I will prepare my strings files (it is even written in your docs, I was not careful when I read it.) But. To be able to provide my custom values I need original keys. And I am gonna take them from your original files.  I opened framework in a Finder like you tell me. 
![2016-03-17 21 17 12](https://cloud.githubusercontent.com/assets/17902236/13856443/aa1d2966-ec8e-11e5-950f-7f8278754b81.png) 
Then I use Xcode to open the file and see this picture.  Not the files I saw when they were directly in Xcode tree. So how can I open original strings? 
![2016-03-17 21 18 09](https://cloud.githubusercontent.com/assets/17902236/13856526/0479b172-ec8f-11e5-8910-a4d857dab1c0.png)

**Comment by mspensieri** [comment]
Hmm you're right, it bundles the compiled strings... We'll be sure to add those keys to the docs. For the meantime, you can use the attached files:

[SmoochLocalization.zip](https://github.com/smooch/smooch-ios/files/178454/SmoochLocalization.zip)

**Comment by MolevD** [comment]
@mspensieri Thank you! These files in a Zip are exactly what I was looking for. I will use them as a reference to create my own.  Do you think it will work? No other consequences if there are no such files with keys in a bundle?

**Comment by mspensieri** [comment]
Nope, there shouldn't be any other consequences. You can include, one, two, or all of those languages. In each of those files, you can include one, two, or all translations. It doesn't matter - if Smooch finds your custom ones it will use them, otherwise it will use the default ones.

**Comment by MolevD** [comment]
@mspensieri Great!
