### ISSUE TITLE
Switching users do not work with `newConversationViewController`

### ISSUE THREAD

**Issue by bartoszhernas** [smooch/smooch-ios#92]
Hey, as I have mentioned earlier, in my app there can be multiple users (like in Twitter app for example).

Whenever I am changing users I am calling `Smooch.login()`.
I have realized now that this is not working because of this warning:
```
<SMOOCH::WARNING> Tried to switch users while on the conversation screen. Ignoring!
```

This should not happen because there is only one place where I call `newConversationViewController`.

My `ChatViewController`, the only place to show Smooch chat. As you can see I am making sure the chat is deallocated. Any ideas?

```
import AhoyUI
import AhoyAPI
import Google
import RxSwift
import RealmSwift
import FontAwesomeKit
import SVProgressHUD

class ChatViewController: AhoyViewController {
    var conversationVC:UIViewController?
    var notificationDisposable:Disposable?
    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Chat"
        self.navigationItem.title = "CHAT"
        self.analyticsTitle = "Chat"
    }
    
    func setUpSmooch() {
        self.tearDownSmooch()
        
        let smoochVC = Smooch.newConversationViewController()
        self.addChildViewController(smoochVC)
        self.view.addSubview(smoochVC.view)
        self.conversationVC = smoochVC
    }
    
    func tearDownSmooch() {
        if let smoochVC = self.conversationVC {
            smoochVC.view.removeFromSuperview()
            smoochVC.removeFromParentViewController()
            self.conversationVC = nil
            Smooch.close() // not sure if this is needed, probably not but I was desperate. Still, did not help
        }
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        self.conversationVC?.view.frame = self.view.bounds
    }
    
    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        self.setUpSmooch()
    }
    
    override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)
        self.tearDownSmooch()
    }
}
```

Any ideas what may be wrong?

**Comment by bartoszhernas** [comment]
I have even tried to initialize Smooch from scratch every time, it still fails, though. 
If I have never seen chat window then it's fine. But once I have invoked `Smooch.newConversationViewController` then is will never allow me to switch users

**Comment by bartoszhernas** [comment]
I do not know why this was the issue, but adding `weak` to property holding the smooch controller fixed the issue. 

It is misbehaviour since I was manually nilling out this property. Smooch Team, could you confirm if this is Apple's error or yours? 

Nevertheless, it is worth noting in docs as well :)

Latest working code:

```
class ChatViewController: AhoyViewController {
    weak var conversationVC:UIViewController?
    
    func setUpSmooch() {
        let smoochVC = Smooch.newConversationViewController()
        self.view.addSubview(smoochVC.view)
        self.addChildViewController(smoochVC)
        self.conversationVC = smoochVC
    }
    
    func tearDownSmooch() {
        if let smoochVC = self.conversationVC {
            smoochVC.removeFromParentViewController()
            smoochVC.view.removeFromSuperview()
        }
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        self.conversationVC?.view.frame = self.view.bounds
    }
    
    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        self.setUpSmooch()
    }
    
    override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)
        self.tearDownSmooch()
    }
}
```

**Comment by mspensieri** [comment]
`conversationShown` is set to `false` in `viewDidDisappear:` of the conversation view controller, so as long as that view controller lifecycle method is called, it should work correctly. Deallocating the instance shouldn't be required...

**Comment by bartoszhernas** [comment]
@mspensieri Thanks for the detailed info. I was nilling out the view controller in `viewWillDisappear` so maybe that's why the `viewDidDisappear` has never been called.

> However, you do still need to get a fresh instance by calling newConversationViewController again after a successful call to login or logout

Yeap, this one I know, thanks a lot!
