### ISSUE TITLE
Notification when Smooch.show() completes

### ISSUE THREAD

**Issue by jamesallison** [smooch/smooch-ios#93]
Some of my users have a lot of messages, and it takes a second to load the `Smooch.show()` modal.

During this short time, it would be good if I could display a loading indicator, then a completion block from the `.show()` function when it has loaded could disable the loading indicator.

**Comment by mspensieri** [comment]
You can use the new delegate method `conversation:didShowViewController:` added in v4.1.0 for this.

How long does it take the conversation to load, maybe there's something we need to optimize? Also, can you define _a lot of messages_?  :)

**Comment by jamesallison** [comment]
Oh awesome! I've had a user reporting that it takes around 3 seconds to load his conversation. I'll PM you in Slack with the userid.
