### ISSUE TITLE
Slack does not show message from smooch sometimes

### ISSUE THREAD

**Issue by beingshashi** [smooch/smooch-ios#94]
Hi,

we have integrated our smooch to slack ,on one of the public channel know as "#support" , so whenver someone sends messages from our app using smooch chat ui , it will be visible on slack in "#support" , channel , also it will create channel with name of the user like "#sk-test-user".

But sometimes we have observed that message send from smooch doesn't show up in "#support" , though it is visible on "#sk-test-user".
sometimes it doesnt show up in either channel though we get proper notification of the message. How can this be possible?

we have tried deleting channel "sk-test-user" sometimes , let me know if this causing this issue?

Thanks,

**Comment by mspensieri** [comment]
We've made a number of fixes on the backend side over the last couple weeks to mitigate some errors we were having due to Slack's rate limiting policy, which we observed had changed slightly. This might have been the source of your error. I'll close this issue since it's not related to the iOS SDK, but we're continuing to keep an eye on the Slack integration to see if there are any more errors like this - none have appeared in the last 6 days.

**Comment by patrick-nurt** [comment]
Getting the same error on first message sent from iOS to Slack doesnt show up, got this error in the Smooch logs: ```method_not_supported_for_channel_type```

<img width="1576" alt="screen shot 2019-02-11 at 16 41 12" src="https://user-images.githubusercontent.com/32013747/52563856-f3c0bc00-2e1b-11e9-9e27-b829535153c7.png">

**Comment by patrick-nurt** [comment]
This is how it looks like in Slack:

<img width="613" alt="screen shot 2019-02-11 at 16 45 49" src="https://user-images.githubusercontent.com/32013747/52564106-af81eb80-2e1c-11e9-851e-55e20d2631f2.png">

**Comment by mspensieri** [comment]
@patrick-nurt sounds like a problem with your dispatch channel, has it been deleted or archived? You can assign a new one in the Slack integration page 

![screen shot 2019-02-11 at 8 28 22 am](https://user-images.githubusercontent.com/2286852/52566158-05cc3b80-2dd7-11e9-977c-9050e8952b70.png)

**Comment by patrick-nurt** [comment]
@mspensieri could it be because it's private?

**Comment by mspensieri** [comment]
@patrick-nurt could be, yes
