### ISSUE TITLE
Chat message in text field is not persisted

### ISSUE THREAD

**Issue by bartoszhernas** [smooch/smooch-ios#95]
It's probably a missing feature and not a bug. 

Whenever I recreate `ConversationViewController`, then anything that user has put to the text field, but has not yet sent, is gone.

This would be a nice feature to always persist anything that is in the text field, so if I put "hey, I want to ask about..." and then I close the app and reopen, the text would still be there. This should also fix my issue with recreating view controllers.

**Comment by mspensieri** [comment]
Yep, definitely a feature request :)

Something we've heard before actually, I'll add +1 to the task on your behalf
